import { video } from '../videos/prep.js'

/*
  Module 4 — Reliability & AI.
  A video module: each lesson is a concept video with checks inside, then a module quiz.
*/
const v41 = video({
  id: 'm4-1', title: 'When things break',
  slides: [
    { kind: 'title', icon: 'alert', kicker: 'Module 4 · Video 1', title: 'When things break', sub: 'What a failure really is, and how a workflow can survive one',
      lines: ['Every workflow you build will fail one day.', 'That is not a sign of bad work, it is how connected systems behave.', 'In this lesson you will learn to make a workflow survive failure instead of stopping.'] },
    { kind: 'compare', title: 'Two kinds of failure',
      left: { label: 'Temporary', tone: 'info', cue: 1, points: ['The other system was busy', 'A network hiccup', 'Trying again will work'] },
      right: { label: 'Permanent', tone: 'bad', cue: 3, points: ['The data is wrong', 'The credential expired', 'Trying again will fail again'] },
      lines: ['Start by telling two kinds of failure apart.', 'A temporary failure means the other system was busy, or the network had a hiccup.', 'Trying again a moment later will usually work.', 'A permanent failure means the data is wrong, or a credential has expired.', 'Trying again will simply fail again.'] },
    { kind: 'flow', title: 'By default, one error stops everything',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Trigger', sub: '200 items', cue: 1 },
        { kind: 'data', icon: 'pencil', label: 'Edit Fields', sub: '200 items', cue: 2 },
        { kind: 'logic', icon: 'x-circle', label: 'CRM write', sub: 'fails on item 12', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Notify', sub: 'never runs', cue: 4 },
      ],
      note: { text: 'Item 12 failed, so items 13 to 200 were never tried.', cue: 5 },
      lines: ['Here is what happens with no protection.', 'Two hundred items leave the trigger.', 'They are cleaned as usual.', 'The CRM write fails on item twelve.', 'The whole run stops, and the last node never runs.', 'One bad item has blocked one hundred and eighty-eight good ones.'] },
    { kind: 'define', title: 'Setting 1: retry', term: 'Retry on fail',
      definition: 'A node setting that tries the same step again, after a short wait.',
      parts: [{ text: 'A number of tries', cue: 1 }, { text: 'A wait between them', cue: 2 }, { text: 'For temporary failures', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'Calling back when the line was busy: the same call, a minute later, usually gets through.' },
      lines: ['The first protection is a node setting called retry on fail.', 'You choose a number of tries.', 'You choose a wait between them.', 'And it is the right answer for temporary failures.', 'It is like calling back when the line was busy, because the same call a minute later usually gets through.'] },
    { kind: 'flow', title: 'Setting 2: continue, and keep the failures',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Trigger', sub: '200 items', cue: 1 },
        { kind: 'logic', icon: 'database', label: 'CRM write', sub: 'on error: continue', cue: 2 },
        { kind: 'action', icon: 'send', label: 'Success path', sub: '197 written', cue: 3 },
        { kind: 'action', icon: 'alert', label: 'Error path', sub: '3 to review', cue: 4 },
      ],
      note: { text: 'The good items finish. The failed ones are kept, not lost.', cue: 5 },
      lines: ['The second protection is for permanent failures.', 'Two hundred items arrive.', 'The CRM node is set to continue on error, and to send failures out of a separate error output.', 'One hundred and ninety-seven items are written.', 'Three go down the error path, to be reviewed.', 'The good items finish, and the failed ones are kept instead of lost.'] },
    { kind: 'table', title: 'Which setting, when?',
      columns: ['Situation', 'Setting', 'Why'],
      rows: [
        { cells: ['API busy or slow', 'Retry on fail', 'It will work in a moment'], cue: 1 },
        { cells: ['One row has bad data', 'Continue, with an error output', 'Do not block the rest'], cue: 2 },
        { cells: ['Credential expired', 'Stop, and alert a person', 'Nothing can succeed'], tone: 'bad', cue: 3 },
      ],
      note: { text: 'Match the response to the kind of failure.', cue: 4 },
      lines: ['So which setting do you use, and when?', 'If an API is busy or slow, retry, because it will work in a moment.', 'If one row has bad data, continue with an error output, so the rest are not blocked.', 'If a credential has expired, stop and alert a person, because nothing can succeed until it is fixed.', 'Match the response to the kind of failure.'] },
    { kind: 'example', title: 'In practice: the duplicate invoices',
      scenario: 'An invoice step timed out, was retried, and customers were charged twice.',
      steps: [
        { time: 'Try 1', icon: 'send', text: 'The invoice is created, but the reply is lost', cue: 1 },
        { time: 'Try 2', icon: 'copy', text: 'The retry creates the same invoice again', cue: 2 },
        { time: 'The fix', icon: 'search', text: 'Before creating, check whether it already exists', cue: 3 },
        { time: 'Now', icon: 'database', text: 'A retry finds the invoice and does nothing', cue: 4 },
      ],
      result: { text: 'A step that is retried must be safe to run twice.', cue: 5 },
      lines: ['Retries have one danger, and Nebula met it with invoices.', 'The first try created the invoice, but the reply was lost on the way back.', 'So the retry created the same invoice again.', 'The fix was to check whether the invoice already exists before creating it.', 'Now a retry finds the invoice and does nothing.', 'A step that is retried must be safe to run twice.'] },
    { kind: 'cards', title: 'Surviving failure, everywhere',
      cards: [
        { icon: 'shop', title: 'Shop', flow: ['An order arrives', 'Courier API is busy: retry', 'Label printed a minute late'], cue: 1 },
        { icon: 'file', title: 'Finance', flow: ['Expenses arrive', 'One has no amount: error path', 'The rest are booked'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Readings arrive', 'Database is down: stop and alert', 'An engineer is paged'], cue: 3 },
      ],
      lines: ['The same three responses work in every field.', 'A shop retries a busy courier, and the label is printed a minute late.', 'Finance sends the one bad expense down the error path, and books the rest.', 'A factory stops and pages an engineer when the database is down.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Failures are temporary or permanent', cue: 0 }, { text: 'Retry the temporary ones', cue: 1 }, { text: 'Continue past bad items, and keep them', cue: 2 }, { text: 'Anything retried must be safe to run twice', cue: 3 }],
      lines: ['To sum up, failures are either temporary or permanent.', 'Retry the temporary ones.', 'Continue past bad items, and keep them for review.', 'And anything that is retried must be safe to run twice.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'An API was busy for a few seconds. Which kind of failure is that?', options: ['Temporary', 'Permanent', 'Neither'], correct: 0, explain: 'It will work if tried again shortly — that is what retry is for.', hint: 'Would the same request work a minute later?' },
    { q: 'With no error settings, item 12 of 200 fails. What happens to items 13–200?', options: ['They are processed normally', 'They are never tried', 'They are retried'], correct: 1, explain: 'By default one error stops the whole execution.', hint: 'What does the workflow do by default when a node errors?' },
  ],
  endQuiz: [
    { q: 'One row in 200 has bad data. Which setting keeps the other 199 moving?', options: ['Retry on fail', 'Continue on error, with an error output', 'Stop the workflow'], correct: 1, explain: 'Retrying bad data fails again; continuing keeps the good items moving and saves the bad one.', hint: 'Will trying the same bad row again help?' },
    { q: 'Why can a retry be dangerous?', options: ['It slows the workflow', 'The step may already have happened, so it runs twice', 'It deletes the item'], correct: 1, explain: 'If the first try worked but the reply was lost, the retry repeats it — unless the step checks first.', hint: 'Think of the invoice that was created but never confirmed.' },
  ],
})

const v42 = video({
  id: 'm4-2', title: 'Error workflows',
  slides: [
    { kind: 'title', icon: 'bell-off', kicker: 'Module 4 · Video 2', title: 'Error workflows', sub: 'Making sure a person hears about a failure',
      lines: ['In the last lesson you made single nodes survive failure.', 'But some failures cannot be survived, and somebody has to be told.', 'In this lesson you will build the workflow that tells them.'] },
    { kind: 'compare', title: 'The silent failure',
      left: { label: 'Nobody is told', tone: 'bad', cue: 1, points: ['A workflow fails at 2 AM', 'It stays failed all night', 'A customer finds out first'] },
      right: { label: 'Somebody is told', tone: 'ok', cue: 3, points: ['A workflow fails at 2 AM', 'A message arrives at 2:01', 'It is fixed before breakfast'] },
      lines: ['The worst failure is the silent one.', 'A workflow fails at two in the morning, and nobody is told.', 'It stays failed all night, and a customer finds out first.', 'Now the same failure, but a message arrives one minute later.', 'It is fixed before breakfast, and no customer ever knows.'] },
    { kind: 'define', title: 'What is an error workflow?', term: 'Error workflow',
      definition: 'A separate workflow that runs automatically whenever another workflow fails.',
      parts: [{ text: 'Its own workflow', cue: 1 }, { text: 'Starts with an Error Trigger', cue: 2 }, { text: 'Runs when another one fails', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A smoke alarm: it does nothing all year, and on the one day it matters, it makes sure someone knows.' },
      lines: ['The tool for this is called an error workflow.', 'It is a workflow of its own.', 'It starts with a special node called the Error Trigger.', 'And it runs automatically whenever another workflow fails.', 'It is a smoke alarm, which does nothing all year, and on the one day it matters, makes sure someone knows.'] },
    { kind: 'flow', title: 'How the two workflows connect',
      nodes: [
        { kind: 'logic', icon: 'x-circle', label: 'Any workflow', sub: 'fails', cue: 1 },
        { kind: 'trigger', icon: 'alert', label: 'Error Trigger', sub: 'starts', cue: 2 },
        { kind: 'data', icon: 'pencil', label: 'Build message', sub: 'what and where', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Alert the team', sub: 'Slack or email', cue: 4 },
      ],
      note: { text: 'Set it once in each workflow’s settings: “Error workflow”.', cue: 5 },
      lines: ['Here is how the two connect.', 'Any workflow fails.', 'The Error Trigger in your error workflow starts.', 'A node builds a short message saying what failed and where.', 'And the team is alerted.', 'You connect them once, in each workflow’s settings, under error workflow.'] },
    { kind: 'bullets', title: 'What a good alert contains',
      lead: 'The Error Trigger hands you everything you need.',
      bullets: [
        { icon: 'workflow', text: 'Which workflow failed', cue: 1 },
        { icon: 'boxes', text: 'Which node, and its error message', cue: 2 },
        { icon: 'search', text: 'A link straight to the failed run', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The test', text: 'Could a colleague act on this message without asking you anything?', cue: 4 },
      lines: ['A good alert answers three questions.', 'Which workflow failed.', 'Which node failed, and with what error message.', 'And a link straight to the failed run.', 'The test is whether a colleague could act on the message without asking you anything.'] },
    { kind: 'define', title: 'Raising your own errors', term: 'Stop and Error',
      definition: 'A node that fails the workflow on purpose, with a message you write.',
      parts: [{ text: 'You decide when', cue: 1 }, { text: 'You write the message', cue: 2 }, { text: 'It triggers the alert', cue: 3 }],
      analogy: { label: 'Use it when', text: 'Nothing technically broke, but the result is wrong: zero rows arrived, or a total is negative.' },
      lines: ['Sometimes nothing technically breaks, but the result is still wrong.', 'For that there is a node called Stop and Error, where you decide when it fires.', 'You write the message yourself.', 'And it triggers the same alert as a real failure.', 'Use it when zero rows arrived, or when a total is negative.'] },
    { kind: 'example', title: 'In practice: the report with no data',
      scenario: 'A daily sales report ran “successfully” for a week, with zero sales in it.',
      steps: [
        { time: 'Cause', icon: 'user', text: 'A credential lost access; the API returned nothing', cue: 1 },
        { time: 'Effect', icon: 'mail', text: 'An empty report was emailed every morning', cue: 2 },
        { time: 'The fix', icon: 'split', text: 'IF there are zero rows, Stop and Error', cue: 3 },
        { time: 'Now', icon: 'alert', text: 'The error workflow alerts the team the same day', cue: 4 },
      ],
      result: { text: 'Decide what “wrong” looks like, and make it fail loudly.', cue: 5 },
      lines: ['Here is why that matters.', 'A credential lost access, and the API quietly returned nothing.', 'So an empty report was emailed every morning for a week.', 'The fix was an IF node that checks for zero rows and then uses Stop and Error.', 'Now the error workflow alerts the team the same day.', 'Decide what wrong looks like, and make it fail loudly.'] },
    { kind: 'cards', title: 'Error workflows, everywhere',
      cards: [
        { icon: 'shop', title: 'Shop', flow: ['The order sync fails', 'Error workflow starts', 'The on-call person is messaged'], cue: 1 },
        { icon: 'file', title: 'Finance', flow: ['Invoicing fails', 'Error workflow starts', 'A ticket is opened for finance'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['The sensor import fails', 'Error workflow starts', 'The shift lead is paged'], cue: 3 },
      ],
      lines: ['One error workflow can serve every workflow you own.', 'In a shop, a failed order sync messages the on-call person.', 'In finance, failed invoicing opens a ticket.', 'In a factory, a failed sensor import pages the shift lead.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'A failure nobody hears about is the worst kind', cue: 0 }, { text: 'An error workflow starts with an Error Trigger', cue: 1 }, { text: 'Say what failed, where, and link to the run', cue: 2 }, { text: 'Use Stop and Error when the result is wrong', cue: 3 }],
      lines: ['To sum up, a failure nobody hears about is the worst kind.', 'An error workflow starts with an Error Trigger.', 'A good alert says what failed and where, and links to the run.', 'And use Stop and Error when nothing broke but the result is wrong.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'What starts an error workflow?', options: ['A schedule', 'The Error Trigger, when another workflow fails', 'A person clicking run'], correct: 1, explain: 'It runs automatically whenever a workflow that points to it fails.', hint: 'Think of the smoke alarm: what sets it off?' },
    { q: 'Which is most useful in an alert?', options: ['The workflow, the node, the error and a link to the run', 'The date only', 'A list of every node'], correct: 0, explain: 'A colleague should be able to act on it without asking anything.', hint: 'What would you need at 2 AM to start fixing it?' },
  ],
  endQuiz: [
    { q: 'A report runs green every day but contains zero rows. How do you get alerted?', options: ['Wait for a real error', 'Check for zero rows and use Stop and Error', 'Add more retries'], correct: 1, explain: 'Nothing technically failed, so you raise the error yourself.', hint: 'The workflow thinks everything is fine — who has to say otherwise?' },
    { q: 'How many error workflows do ten workflows need?', options: ['Ten', 'One, shared by all of them', 'None'], correct: 1, explain: 'Each workflow points to the same error workflow in its settings.', hint: 'How many smoke alarms per building, not per room?' },
  ],
})

const v43 = video({
  id: 'm4-3', title: 'AI in the loop',
  slides: [
    { kind: 'title', icon: 'boxes', kicker: 'Module 4 · Video 3', title: 'AI in the loop', sub: 'Using a language model as one careful step in a workflow',
      lines: ['Some jobs cannot be done with rules, because they need reading and judgement.', 'For those you can add an AI model as one step in a workflow.', 'In this lesson you will learn where that helps, and how to keep it under control.'] },
    { kind: 'compare', title: 'Rules, or a model?',
      left: { label: 'Use rules when', tone: 'info', cue: 1, points: ['The answer is in a field', 'The test is exact', '“total over 200”'] },
      right: { label: 'Use a model when', tone: 'info', cue: 3, points: ['The answer is in free text', 'It needs reading', '“is this customer angry?”'] },
      lines: ['First, when do you need a model at all?', 'Use rules when the answer is in a field, and the test is exact.', 'Whether a total is over two hundred needs no intelligence.', 'Use a model when the answer is buried in free text.', 'Whether a customer is angry is something a rule cannot read.'] },
    { kind: 'bullets', title: 'Three jobs a model does well',
      lead: 'Each takes free text in and gives structured data out.',
      bullets: [
        { icon: 'split', text: 'Classify: billing, technical or other', cue: 1 },
        { icon: 'search', text: 'Extract: the order number from an email', cue: 2 },
        { icon: 'pencil', text: 'Summarise: a long thread in two lines', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'Notice', text: 'The output is a field your next node can test, not a paragraph.', cue: 4 },
      lines: ['There are three jobs a model does well inside a workflow.', 'It can classify, for example billing, technical or other.', 'It can extract, for example the order number from an email.', 'And it can summarise a long thread into two lines.', 'In each case the output is a field your next node can test, not a paragraph.'] },
    { kind: 'flow', title: 'A model as one step',
      nodes: [
        { kind: 'trigger', icon: 'headset', label: 'New ticket', sub: 'free text', cue: 1 },
        { kind: 'data', icon: 'boxes', label: 'AI: classify', sub: 'category + urgency', cue: 2 },
        { kind: 'logic', icon: 'split', label: 'Switch', sub: 'by category', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Assign', sub: 'right team', cue: 4 },
      ],
      note: { text: 'The model reads. Ordinary nodes decide and act.', cue: 5 },
      lines: ['Here is a model used as one step.', 'A ticket arrives as free text.', 'The AI node reads it and returns a category and an urgency.', 'A Switch routes it by category.', 'And the ticket is assigned to the right team.', 'The model reads, and ordinary nodes decide and act.'] },
    { kind: 'code', title: 'The prompt is part of your workflow',
      lead: 'A good prompt says what to return, and in what form.',
      rows: [
        { code: 'Classify this ticket: {{ $json.text }}', out: 'the task, with the item’s text', cue: 1 },
        { code: 'Answer with one of: billing, technical, other', out: 'only allowed answers', cue: 2 },
        { code: 'If unsure, answer: other', out: 'a safe way out', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'Why so strict', text: 'The next node tests the answer. It must be one of the values you expect.', cue: 4 },
      lines: ['The instruction you give the model is called a prompt, and it is part of your workflow.', 'It states the task, and uses an expression to include the text of the item.', 'It lists the only answers that are allowed.', 'And it gives the model a safe way out when it is unsure.', 'It is strict because the next node tests the answer, which must be one of the values you expect.'] },
    { kind: 'bullets', title: 'A model can be wrong — plan for it',
      lead: 'Treat its output like data from an outside system: check it.',
      bullets: [
        { icon: 'filter', text: 'Validate: is the answer one of the allowed values?', cue: 1 },
        { icon: 'user', text: 'Human approval before anything irreversible', cue: 2 },
        { icon: 'eye', text: 'Log what it decided, so you can review', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'The rule', text: 'A model may suggest. A person approves refunds, deletions and messages to customers.', cue: 4 },
      lines: ['A model can be wrong, so treat its output like data from an outside system.', 'Validate it, by checking the answer is one of the allowed values.', 'Put a human approval step before anything that cannot be undone.', 'And log what it decided, so you can review it later.', 'The rule is that a model may suggest, but a person approves refunds, deletions and messages to customers.'] },
    { kind: 'example', title: 'In practice: 200 tickets a day',
      scenario: 'Nebula’s support inbox gets 200 tickets a day, all free text.',
      steps: [
        { time: 'Read', icon: 'boxes', text: 'The model returns category and urgency', cue: 1 },
        { time: 'Check', icon: 'filter', text: 'Unexpected answers go to a person', cue: 2 },
        { time: 'Route', icon: 'split', text: 'Routine tickets are assigned automatically', cue: 3 },
        { time: 'Approve', icon: 'user', text: 'Refund requests wait for a human', cue: 4 },
      ],
      result: { text: '180 tickets routed in seconds; 20 handled by people, on purpose.', cue: 5 },
      lines: ['Here is the whole pattern at Nebula, with two hundred tickets a day.', 'The model reads each ticket and returns a category and an urgency.', 'Unexpected answers go straight to a person.', 'Routine tickets are assigned automatically.', 'Refund requests wait for a human to approve.', 'One hundred and eighty are routed in seconds, and twenty are handled by people, on purpose.'] },
    { kind: 'cards', title: 'AI in the loop, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['An invoice PDF arrives', 'Extract supplier and amount', 'A person approves payment'], cue: 1 },
        { icon: 'user', title: 'HR', flow: ['An application arrives', 'Summarise the experience', 'A recruiter decides'], cue: 2 },
        { icon: 'shop', title: 'Shop', flow: ['A review is posted', 'Classify it as praise or complaint', 'Complaints go to a person'], cue: 3 },
      ],
      lines: ['The same pattern works wherever people read text all day.', 'In finance, a model extracts the supplier and amount, and a person approves the payment.', 'In human resources, a model summarises an application, and a recruiter decides.', 'In a shop, a model sorts reviews, and the complaints go to a person.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Use a model for reading, rules for exact tests', cue: 0 }, { text: 'Ask for a fixed set of answers', cue: 1 }, { text: 'Validate the output before using it', cue: 2 }, { text: 'A person approves what cannot be undone', cue: 3 }],
      lines: ['To sum up, use a model for reading, and rules for exact tests.', 'Ask for a fixed set of answers.', 'Validate the output before using it.', 'And a person approves anything that cannot be undone.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'Which job needs a model rather than a rule?', options: ['Is the total over 200?', 'Is this free-text message a complaint?', 'Is the email field empty?'], correct: 1, explain: 'A rule can test a field exactly; reading meaning from free text needs a model.', hint: 'Which one cannot be answered by comparing a field with a value?' },
    { q: 'Why tell the model to answer with one of a fixed list?', options: ['It is cheaper', 'So the next node can test the answer reliably', 'Models cannot write sentences'], correct: 1, explain: 'A Switch can only route answers it expects.', hint: 'What comes straight after the AI node?' },
  ],
  endQuiz: [
    { q: 'The model returns “maybe billing?”. What should the workflow do?', options: ['Route it to billing', 'Send it to a person, because it is not an allowed answer', 'Run the model again until it changes'], correct: 1, explain: 'Validate the output; anything unexpected goes to a human.', hint: 'Is that one of the values you asked for?' },
    { q: 'Which action should always wait for human approval?', options: ['Adding a label to a ticket', 'Issuing a refund', 'Writing a log line'], correct: 1, explain: 'A model may suggest; a person approves what cannot be undone.', hint: 'Which of these is hard to take back?' },
  ],
})

export default {
  id: 'm4', n: 4, lite: true,
  title: 'Reliability & AI',
  submodules: [
    { id: '4.1', title: 'When things break', video: v41 },
    { id: '4.2', title: 'Error workflows', video: v42 },
    { id: '4.3', title: 'AI in the loop', video: v43 },
  ],
  quiz: {
    passMark: 0.66,
    teachbackPrompt: 'Explain to a teammate how you would make a workflow you depend on fail safely and loudly.',
    questions: [
      { sub: '4.1', q: 'A courier API times out now and then. Best setting?', options: ['Retry on fail, with a wait', 'Stop the workflow', 'Ignore the error'], correct: 0, explain: 'A temporary failure usually works on a second try.' },
      { sub: '4.1', q: 'A step that is retried must be…', options: ['Fast', 'Safe to run twice', 'The last node'], correct: 1, explain: 'If the first try worked but the reply was lost, the retry repeats it.' },
      { sub: '4.2', q: 'What makes an error workflow run?', options: ['A schedule', 'Another workflow failing', 'A webhook'], correct: 1, explain: 'It starts with an Error Trigger and runs when a linked workflow fails.' },
      { sub: '4.2', q: 'Zero rows arrived, but nothing errored. How do you raise the alarm?', options: ['Retry', 'Stop and Error', 'Merge'], correct: 1, explain: 'Stop and Error fails the workflow on purpose, with your own message.' },
      { sub: '4.3', q: 'What should an AI step in a workflow return?', options: ['A long explanation', 'A value from a fixed list the next node can test', 'Nothing'], correct: 1, explain: 'Structured, expected output keeps the rest of the workflow reliable.' },
      { sub: '4.3', q: 'A model suggests refunding a customer. What happens next?', options: ['The refund is issued', 'A person approves or rejects it', 'The workflow stops'], correct: 1, explain: 'Irreversible actions wait for human approval.' },
    ],
  },
  reviews: [],
}
