import { video } from '../videos/prep.js'

/*
  Module 5 — Bigger Workflows: Reuse, Code & Files.
  A video module: each lesson is a concept video with checks inside, then a module quiz.
*/
const v51 = video({
  id: 'm5-1', title: 'Sub-workflows',
  slides: [
    { kind: 'title', icon: 'workflow', kicker: 'Module 5 · Video 1', title: 'Sub-workflows', sub: 'Building once, and reusing everywhere',
      lines: ['As your automations grow, two problems appear.', 'Workflows become too large to read, and the same steps get built again and again.', 'In this lesson you will solve both with sub-workflows.'] },
    { kind: 'compare', title: 'Copying, or reusing',
      left: { label: 'Copy the steps', tone: 'bad', cue: 1, points: ['The cleaning steps exist in 5 workflows', 'A rule changes', 'You fix it 5 times, and miss one'] },
      right: { label: 'Reuse one sub-workflow', tone: 'ok', cue: 3, points: ['The cleaning steps exist once', 'A rule changes', 'You fix it once, everywhere'] },
      lines: ['Imagine your email cleaning steps are needed in five workflows.', 'If you copy them, they exist five times.', 'When a rule changes, you fix it five times, and probably miss one.', 'If you reuse one sub-workflow, the steps exist once.', 'When a rule changes, you fix it once, and it is fixed everywhere.'] },
    { kind: 'define', title: 'What is a sub-workflow?', term: 'Sub-workflow',
      definition: 'A workflow that is started by another workflow, does one job, and hands its result back.',
      parts: [{ text: 'Called by a parent', cue: 1 }, { text: 'Does one job', cue: 2 }, { text: 'Returns its result', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A specialist you send work to: you hand over a file, they do their part, and the file comes back.' },
      lines: ['So what is a sub-workflow?', 'It is a workflow that is called by another one, which we call the parent.', 'It does one job.', 'And it returns its result to the parent.', 'Think of a specialist you send work to, where you hand over a file, they do their part, and the file comes back.'] },
    { kind: 'flow', title: 'How the call works',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Parent', sub: '500 items', cue: 1 },
        { kind: 'data', icon: 'workflow', label: 'Execute Sub-workflow', sub: 'sends 500', cue: 2 },
        { kind: 'logic', icon: 'pencil', label: 'Sub-workflow', sub: 'cleans them', cue: 3 },
        { kind: 'action', icon: 'database', label: 'Parent continues', sub: '462 back', cue: 4 },
      ],
      note: { text: 'The parent waits, then carries on with what came back.', cue: 5 },
      lines: ['Here is how the call works.', 'The parent workflow holds five hundred items.', 'A node called Execute Sub-workflow sends them across.', 'The sub-workflow cleans them, starting from its own special trigger.', 'And the parent continues with the four hundred and sixty-two that came back.', 'The parent waits, then carries on with whatever was returned.'] },
    { kind: 'bullets', title: 'What makes a good sub-workflow',
      lead: 'Pull a group of nodes out when it has these three properties.',
      bullets: [
        { icon: 'boxes', text: 'One clear job: “clean customer records”', cue: 1 },
        { icon: 'download', text: 'A clear input: which fields it expects', cue: 2 },
        { icon: 'send', text: 'A clear output: which fields it returns', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'A useful test', text: 'If you can name it in three words, it is probably one job.', cue: 4 },
      lines: ['What should you pull out into a sub-workflow?', 'Something with one clear job, such as clean customer records.', 'Something with a clear input, meaning the fields it expects.', 'And something with a clear output, meaning the fields it returns.', 'A useful test is that if you can name it in three words, it is probably one job.'] },
    { kind: 'compare', title: 'One giant workflow, or small parts',
      left: { label: 'One workflow, 60 nodes', tone: 'bad', cue: 1, points: ['Hard to read', 'One change risks everything', 'Tested only as a whole'] },
      right: { label: 'A parent and 4 sub-workflows', tone: 'ok', cue: 3, points: ['Each part fits on one screen', 'A change stays in its part', 'Each part is tested alone'] },
      lines: ['Reuse is only half the benefit.', 'A single workflow with sixty nodes is hard to read, and one change risks everything.', 'It can only be tested as a whole.', 'Split into a parent and four sub-workflows, each part fits on one screen.', 'And each part can be tested alone, with its own sample data.'] },
    { kind: 'example', title: 'In practice: one cleaner, three users',
      scenario: 'Nebula cleans customer data in three places: sign-ups, imports and the CRM sync.',
      steps: [
        { time: 'Before', icon: 'copy', text: 'Three copies of the cleaning steps, slightly different', cue: 1 },
        { time: 'Extract', icon: 'workflow', text: 'One “Clean customers” sub-workflow', cue: 2 },
        { time: 'Call', icon: 'send', text: 'All three workflows call it', cue: 3 },
        { time: 'Later', icon: 'pencil', text: 'A new date format is handled in one place', cue: 4 },
      ],
      result: { text: 'Three workflows got shorter, and all three now clean data the same way.', cue: 5 },
      lines: ['Here is the idea at Nebula, where customer data is cleaned in three places.', 'Before, there were three copies of the cleaning steps, each slightly different.', 'They were pulled out into one sub-workflow called clean customers.', 'Now all three workflows call it.', 'Later, when a new date format appeared, it was handled in one place.', 'Three workflows got shorter, and all three now clean data the same way.'] },
    { kind: 'cards', title: 'Sub-workflows, everywhere',
      cards: [
        { icon: 'send', title: 'Notify', flow: ['Any workflow needs to alert', 'Call “Notify the team”', 'One place sets the channel'], cue: 1 },
        { icon: 'search', title: 'Look up', flow: ['An order needs its customer', 'Call “Find customer”', 'The customer comes back'], cue: 2 },
        { icon: 'filter', title: 'Validate', flow: ['A record arrives', 'Call “Check address”', 'Valid, or a reason why not'], cue: 3 },
      ],
      lines: ['Three kinds of sub-workflow turn up in almost every team.', 'A notify sub-workflow, so one place decides which channel alerts go to.', 'A look-up sub-workflow, which takes an order and returns its customer.', 'And a validate sub-workflow, which returns valid, or a reason why not.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'A sub-workflow does one job for a parent', cue: 0 }, { text: 'Build once, reuse everywhere', cue: 1 }, { text: 'Give it a clear input and output', cue: 2 }, { text: 'Small parts are easier to read and test', cue: 3 }],
      lines: ['To sum up, a sub-workflow does one job for a parent workflow.', 'Build it once, and reuse it everywhere.', 'Give it a clear input and a clear output.', 'And remember that small parts are easier to read and to test.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'The same cleaning steps are copied into five workflows. What is the main risk?', options: ['They run more slowly', 'A change must be made five times, and one gets missed', 'They use more credentials'], correct: 1, explain: 'Copies drift apart; one shared sub-workflow is fixed once.', hint: 'What happens the day a rule changes?' },
    { q: 'What does the parent workflow do while the sub-workflow runs?', options: ['It carries on without waiting', 'It waits, then continues with what came back', 'It stops for good'], correct: 1, explain: 'The Execute Sub-workflow node hands over the items and receives the result.', hint: 'Think of the specialist returning the file.' },
  ],
  endQuiz: [
    { q: 'Which group of nodes is the best candidate for a sub-workflow?', options: ['Steps that do one clear job used in several workflows', 'The trigger', 'Any three nodes in a row'], correct: 0, explain: 'One job, a clear input and a clear output — and needed in more than one place.', hint: 'Could you name it in three words?' },
    { q: 'Besides reuse, what does splitting a 60-node workflow give you?', options: ['Fewer items', 'Parts that can be read and tested on their own', 'No need for a trigger'], correct: 1, explain: 'Each part fits on a screen and can be tested alone.', hint: 'What is hard about changing one node among sixty?' },
  ],
})

const v52 = video({
  id: 'm5-2', title: 'The Code node',
  slides: [
    { kind: 'title', icon: 'code', kicker: 'Module 5 · Video 2', title: 'The Code node', sub: 'A few lines of your own, for when no node fits',
      lines: ['Almost everything can be built from ready-made nodes.', 'Almost, but not quite everything.', 'In this lesson you will meet the Code node, and learn when to use it and when not to.'] },
    { kind: 'compare', title: 'A node, or code?',
      left: { label: 'Use a node when', tone: 'ok', cue: 1, points: ['One exists for the job', 'A teammate should read it at a glance', 'Rename, filter, merge, sort'] },
      right: { label: 'Use code when', tone: 'info', cue: 3, points: ['No node does it', 'It would take ten nodes', 'A custom calculation or reshaping'] },
      lines: ['The first question is always whether you need code at all.', 'Use a node when one exists for the job, because a teammate can read it at a glance.', 'Renaming, filtering, merging and sorting all have nodes.', 'Use code when no node does the job, or when it would take ten nodes.', 'A custom calculation or an unusual reshaping are good examples.'] },
    { kind: 'define', title: 'What is the Code node?', term: 'Code node',
      definition: 'A node that runs a few lines of JavaScript on the items passing through.',
      parts: [{ text: 'Receives items', cue: 1 }, { text: 'Runs your lines', cue: 2 }, { text: 'Must return items', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A blank station on the conveyor belt: parcels arrive, you decide what happens, parcels must leave.' },
      lines: ['The Code node runs a few lines of JavaScript.', 'It receives items like any other node.', 'It runs the lines you wrote.', 'And it must return items, so the next node has something to work with.', 'Think of a blank station on the conveyor belt, where parcels arrive, you decide what happens, and parcels must leave.'] },
    { kind: 'table', title: 'Two ways it can run',
      columns: ['Mode', 'Your code sees', 'Good for'],
      rows: [
        { cells: ['Run once for each item', 'One item at a time', 'Changing every item'], cue: 1 },
        { cells: ['Run once for all items', 'The whole list', 'Totals, sorting, grouping'], cue: 2 },
      ],
      note: { text: 'Pick the mode first; it decides how you write the code.', cue: 3 },
      lines: ['The Code node can run in two ways.', 'Run once for each item means your code sees one item at a time, which is good for changing every item.', 'Run once for all items means your code sees the whole list, which is good for totals, sorting and grouping.', 'Pick the mode first, because it decides how you write the code.'] },
    { kind: 'code', title: 'For each item: add a field',
      lead: 'Mode: run once for each item.',
      rows: [
        { code: 'const total = $json.price * $json.qty', out: 'work out a value', cue: 1 },
        { code: '$json.total = total', out: 'add it to the item', cue: 2 },
        { code: 'return $json', out: 'hand the item back', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'Do not forget', text: 'If nothing is returned, nothing reaches the next node.', cue: 4 },
      lines: ['Here is the simplest useful example, in the mode for each item.', 'The first line works out a total from the price and the quantity.', 'The second adds that total to the item as a new field.', 'The third hands the item back.', 'Do not forget that last line, because if nothing is returned, nothing reaches the next node.'] },
    { kind: 'code', title: 'For all items: one summary',
      lead: 'Mode: run once for all items.',
      rows: [
        { code: 'const items = $input.all()', out: 'the whole list', cue: 1 },
        { code: 'const sum = items.reduce(…)', out: 'add up every total', cue: 2 },
        { code: 'return [{ json: { sum } }]', out: 'one item comes out', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'Notice', text: '500 items in, 1 item out. Count items after a Code node, as after any other.', cue: 4 },
      lines: ['And here is the other mode, working on all items at once.', 'The first line takes the whole list.', 'The second adds up every total.', 'The third returns a single item holding the sum.', 'Notice that five hundred items went in and one came out, so count items after a Code node as you would after any other.'] },
    { kind: 'bullets', title: 'Keeping code under control',
      lead: 'Code is powerful, and harder for the next person to read.',
      bullets: [
        { icon: 'pencil', text: 'Name the node after what it does', cue: 1 },
        { icon: 'boxes', text: 'Keep it short: one job per Code node', cue: 2 },
        { icon: 'x-circle', text: 'No passwords or keys in the code', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The test', text: 'If a node exists for it, use the node.', cue: 4 },
      lines: ['Code is powerful, but it is harder for the next person to read.', 'So name the node after what it does.', 'Keep it short, with one job in each Code node.', 'And never put passwords or keys in the code.', 'The final test is simple, which is that if a node exists for the job, use the node.'] },
    { kind: 'cards', title: 'Good uses of the Code node',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['Invoices arrive', 'Code: tax by country rules', 'Save the totals'], cue: 1 },
        { icon: 'shop', title: 'Shop', flow: ['Orders arrive', 'Code: group lines by order', 'One item per order'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Readings arrive', 'Code: average of the last ten', 'Alert on a jump'], cue: 3 },
      ],
      lines: ['Here are three good uses.', 'In finance, a tax calculation with rules that differ by country.', 'In a shop, grouping order lines so that each order becomes one item.', 'In a factory, an average of the last ten readings, to alert on a sudden jump.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Use a node if one exists; code if none does', cue: 0 }, { text: 'Choose the mode: each item, or all items', cue: 1 }, { text: 'Always return items', cue: 2 }, { text: 'Short, named, and free of secrets', cue: 3 }],
      lines: ['To sum up, use a node if one exists, and code if none does.', 'Choose the mode, which is each item or all items.', 'Always return items.', 'And keep your code short, named, and free of secrets.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'When is the Code node the right choice?', options: ['Whenever possible', 'When no node does the job, or it would take many nodes', 'Never'], correct: 1, explain: 'Nodes are easier to read; code is for what they cannot do.', hint: 'Which is easier for a teammate to read at a glance?' },
    { q: 'You need one grand total across 500 items. Which mode?', options: ['Run once for each item', 'Run once for all items', 'Either gives the same result'], correct: 1, explain: 'A total needs the whole list at once.', hint: 'Does your code need to see one item, or all of them?' },
  ],
  endQuiz: [
    { q: 'The node after a Code node receives nothing. Most likely cause?', options: ['The code did not return any items', 'The trigger is wrong', 'There are too many items'], correct: 0, explain: 'A Code node must return items for the next node.', hint: 'What is the last line of the code?' },
    { q: 'Where should an API key used by your code live?', options: ['In the code', 'In a credential, not in the code', 'In a comment'], correct: 1, explain: 'Secrets never go in code or node parameters.', hint: 'Who can read the code when the workflow is shared?' },
  ],
})

const v53 = video({
  id: 'm5-3', title: 'Files and binary data',
  slides: [
    { kind: 'title', icon: 'file', kicker: 'Module 5 · Video 3', title: 'Files and binary data', sub: 'PDFs, spreadsheets and attachments inside a workflow',
      lines: ['So far every item has been made of fields.', 'But real work is full of files, such as invoices, spreadsheets and photos.', 'In this lesson you will learn how a workflow carries files, and how to get data out of them.'] },
    { kind: 'compare', title: 'Two kinds of data in one item',
      left: { label: 'JSON data', tone: 'info', cue: 1, points: ['Fields with names', 'name, email, total', 'Nodes can read it directly'] },
      right: { label: 'Binary data', tone: 'info', cue: 3, points: ['A whole file', 'invoice.pdf, photo.jpg', 'Carried along, not read'] },
      lines: ['An item can actually carry two kinds of data.', 'The first is the kind you know, with named fields such as name, email and total.', 'Nodes can read it directly.', 'The second is binary data, which is a whole file such as a PDF or a photo.', 'The file is carried along with the item, but nodes cannot read inside it.'] },
    { kind: 'define', title: 'What is binary data?', term: 'Binary data',
      definition: 'A file attached to an item: carried through the workflow, but not readable as fields.',
      parts: [{ text: 'Travels with the item', cue: 1 }, { text: 'Has a name and a type', cue: 2 }, { text: 'Must be extracted to be read', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A sealed envelope clipped to a form: it goes wherever the form goes, but you must open it to read it.' },
      lines: ['Here is the definition.', 'Binary data is a file that travels with the item.', 'It has a file name and a type.', 'And it must be extracted before its contents can be read.', 'Picture a sealed envelope clipped to a form, which goes wherever the form goes, but must be opened to be read.'] },
    { kind: 'flow', title: 'Getting data out of a file',
      nodes: [
        { kind: 'trigger', icon: 'mail', label: 'Email arrives', sub: 'orders.csv attached', cue: 1 },
        { kind: 'data', icon: 'file', label: 'Extract from File', sub: 'CSV → rows', cue: 2 },
        { kind: 'logic', icon: 'filter', label: 'Filter', sub: 'valid rows', cue: 3 },
        { kind: 'action', icon: 'database', label: 'Save orders', sub: '120 items', cue: 4 },
      ],
      note: { text: 'One file went in; 120 ordinary items came out.', cue: 5 },
      lines: ['Here is how you open the envelope.', 'An email arrives with a spreadsheet file attached.', 'A node called Extract from File turns the file into rows.', 'From here on everything is familiar, so a Filter keeps the valid rows.', 'And the orders are saved.', 'One file went in, and one hundred and twenty ordinary items came out.'] },
    { kind: 'table', title: 'The file nodes you will use',
      columns: ['Node', 'What it does', 'Example'],
      rows: [
        { cells: ['Extract from File', 'File → items', 'CSV, Excel or PDF text'], cue: 1 },
        { cells: ['Convert to File', 'Items → file', 'A report as CSV'], cue: 2 },
        { cells: ['Read / Write Files', 'Load or save a file', 'Keep a copy on disk'], cue: 3 },
      ],
      note: { text: 'Extract to work with the data; convert to send it on.', cue: 4 },
      lines: ['Three nodes cover most file work.', 'Extract from File turns a file into items, and it handles CSV, Excel and the text of a PDF.', 'Convert to File does the opposite, turning items into a file such as a report.', 'And the read and write nodes load or save a file.', 'Extract when you want to work with the data, and convert when you want to send it on.'] },
    { kind: 'flow', title: 'Building a file to send',
      nodes: [
        { kind: 'trigger', icon: 'clock', label: 'Every Monday', sub: '8 AM', cue: 1 },
        { kind: 'data', icon: 'database', label: 'Get sales', sub: '340 items', cue: 2 },
        { kind: 'data', icon: 'file', label: 'Convert to File', sub: 'sales.csv', cue: 3 },
        { kind: 'action', icon: 'mail', label: 'Email', sub: 'file attached', cue: 4 },
      ],
      note: { text: '340 items went in; one item with one file came out.', cue: 5 },
      lines: ['Now the other direction.', 'Every Monday at eight the workflow starts.', 'It fetches three hundred and forty sales records.', 'Convert to File turns them into one spreadsheet file.', 'And an email goes out with the file attached.', 'Three hundred and forty items went in, and one item with one file came out.'] },
    { kind: 'bullets', title: 'Three things that go wrong with files',
      lead: 'Each has a simple check.',
      bullets: [
        { icon: 'x-circle', text: 'A node drops the file: check it is still attached', cue: 1 },
        { icon: 'search', text: 'The wrong file type arrives: test the type first', cue: 2 },
        { icon: 'alert', text: 'A scanned PDF has no text to extract', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The habit', text: 'After each node, look for the file as well as the fields.', cue: 4 },
      lines: ['Three things commonly go wrong with files.', 'A node in the middle drops the file, so check that it is still attached.', 'The wrong file type arrives, so test the type before extracting.', 'And a scanned PDF is only a picture, with no text to extract.', 'So after each node, look for the file as well as the fields.'] },
    { kind: 'cards', title: 'Files, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['An invoice PDF arrives', 'Extract its text', 'Save amount and supplier'], cue: 1 },
        { icon: 'user', title: 'HR', flow: ['A CV is uploaded', 'Store the file', 'Notify the recruiter'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['The shift ends', 'Convert readings to a CSV', 'Email it to the manager'], cue: 3 },
      ],
      lines: ['Files appear in every department.', 'Finance extracts the text of an invoice and saves the amount and the supplier.', 'Human resources stores an uploaded CV and notifies the recruiter.', 'A factory converts the readings of a shift into a file and emails it to the manager.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'An item can carry fields and a file', cue: 0 }, { text: 'Extract from File turns a file into items', cue: 1 }, { text: 'Convert to File turns items into a file', cue: 2 }, { text: 'Check the file is still there after each node', cue: 3 }],
      lines: ['To sum up, an item can carry fields and a file.', 'Extract from File turns a file into items.', 'Convert to File turns items into a file.', 'And check that the file is still there after each node.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'What is binary data?', options: ['A field with a number in it', 'A file attached to an item', 'An error message'], correct: 1, explain: 'It is a whole file — a PDF, a spreadsheet, a photo — carried with the item.', hint: 'Think of the sealed envelope clipped to the form.' },
    { q: 'A CSV file arrives by email. Which node turns it into rows?', options: ['Convert to File', 'Extract from File', 'Merge'], correct: 1, explain: 'Extract from File goes from a file to items.', hint: 'You want to get data out of the file.' },
  ],
  endQuiz: [
    { q: '340 items go into Convert to File. What comes out?', options: ['340 files', 'One item with one file', 'Nothing'], correct: 1, explain: 'The items are written into a single file.', hint: 'How many spreadsheets does one report need?' },
    { q: 'Extracting text from a PDF returns nothing. Likely reason?', options: ['The PDF is a scanned image', 'The workflow has no trigger', 'PDFs cannot be attached'], correct: 0, explain: 'A scan is a picture; there is no text layer to extract.', hint: 'Is there any text in the file, or just a photo of text?' },
  ],
})

export default {
  id: 'm5', n: 5, lite: true,
  title: 'Bigger Workflows: Reuse, Code & Files',
  submodules: [
    { id: '5.1', title: 'Sub-workflows', video: v51 },
    { id: '5.2', title: 'The Code node', video: v52 },
    { id: '5.3', title: 'Files and binary data', video: v53 },
  ],
  quiz: {
    passMark: 0.66,
    teachbackPrompt: 'Explain to a teammate how you would split a large workflow into parts.',
    questions: [
      { sub: '5.1', q: 'Why move repeated steps into a sub-workflow?', options: ['To fix them once instead of in every copy', 'To make them run twice', 'To avoid using a trigger'], correct: 0, explain: 'One shared sub-workflow means one place to change.' },
      { sub: '5.1', q: 'What does a good sub-workflow have?', options: ['As many jobs as possible', 'One job, a clear input and a clear output', 'No output'], correct: 1, explain: 'That is what makes it reusable and testable.' },
      { sub: '5.2', q: 'A node exists for the job. Should you use the Code node instead?', options: ['Yes, code is always better', 'No — use the node', 'Only on Mondays'], correct: 1, explain: 'Nodes are easier for others to read and maintain.' },
      { sub: '5.2', q: 'What must every Code node do?', options: ['Return items', 'Call an API', 'Contain a password'], correct: 0, explain: 'Without returned items the next node receives nothing.' },
      { sub: '5.3', q: 'Which node turns a spreadsheet file into items?', options: ['Extract from File', 'Convert to File', 'Switch'], correct: 0, explain: 'Extract: file → items. Convert: items → file.' },
      { sub: '5.3', q: 'After a node in the middle, the attachment is gone. What do you check?', options: ['Whether that node passed the file on', 'The trigger schedule', 'The workflow name'], correct: 0, explain: 'A file travels with the item only if each node keeps it attached.' },
    ],
  },
  reviews: [],
}
