import { video } from '../videos/prep.js'

/*
  Module 3 — Logic, Branching & APIs.
  A video module: each lesson is a concept video with checks inside, then a module quiz.
  (Worked builds, scenario sets and guided practice are not written for it yet.)
*/
const v31 = video({
  id: 'm3-1', title: 'Conditional logic: IF and Switch',
  slides: [
    { kind: 'title', icon: 'split', kicker: 'Module 3 · Video 1', title: 'Conditional logic', sub: 'Sending different items down different paths',
      lines: ['Until now your workflows have run in one straight line.', 'In this lesson they learn to choose.', 'You will meet two nodes that send different items down different paths.'] },
    { kind: 'compare', title: 'Stop it, or route it?',
      left: { label: 'Filter', tone: 'info', cue: 1, points: ['One way out', 'Items that fail are dropped', 'Use it to guard'] },
      right: { label: 'IF', tone: 'info', cue: 3, points: ['Two ways out: true and false', 'Every item goes somewhere', 'Use it to route'] },
      lines: ['You already know the Filter.', 'It has one way out, and items that fail the test are simply dropped.', 'That is right for a guard, but sometimes you want to keep both groups.', 'The IF node has two ways out, one for true and one for false.', 'Every item goes somewhere, so nothing is lost.'] },
    { kind: 'define', title: 'What is a branch?', term: 'Branch',
      definition: 'A separate path through the workflow that only some items take.',
      parts: [{ text: 'Starts at a decision', cue: 1 }, { text: 'Has its own nodes', cue: 2 }, { text: 'Only some items take it', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A sorting office: every parcel is read once, then sent down the belt for its own destination.' },
      lines: ['Each way out of a decision is called a branch.', 'A branch starts at a decision node.', 'It has its own nodes.', 'And only some of the items take it.', 'Picture a sorting office, where every parcel is read once and then sent down the belt for its own destination.'] },
    { kind: 'flow', title: 'IF: one question, two paths',
      nodes: [
        { kind: 'trigger', icon: 'shop', label: 'New order', sub: '10 items', cue: 1 },
        { kind: 'logic', icon: 'split', label: 'IF', sub: 'total over 200', cue: 2 },
        { kind: 'action', icon: 'send', label: 'True: VIP team', sub: '3 items', cue: 3 },
        { kind: 'action', icon: 'mail', label: 'False: standard', sub: '7 items', cue: 4 },
      ],
      note: { text: '10 in, 3 one way and 7 the other. Nothing is dropped.', cue: 5 },
      lines: ['Here is the IF node at work.', 'Ten orders arrive.', 'The IF node asks one question, which is whether the total is over two hundred.', 'Three orders answer yes, and go to the VIP team.', 'Seven answer no, and get the standard confirmation.', 'Ten in, three one way and seven the other, with nothing dropped.'] },
    { kind: 'bullets', title: 'Writing the condition',
      lead: 'A condition compares a field with a value.',
      bullets: [
        { icon: 'table', text: 'The field: total, plan, country', cue: 1 },
        { icon: 'search', text: 'The test: equals, is greater than, contains', cue: 2 },
        { icon: 'boxes', text: 'The value: 200, “pro”, “DE”', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'Watch the type', text: 'The text “200” and the number 200 are not the same thing. Compare numbers as numbers.', cue: 4 },
      lines: ['A condition is made of three parts.', 'First the field you are testing, such as the total.', 'Then the test, such as equals, is greater than, or contains.', 'And then the value to compare with.', 'One warning: the text two hundred and the number two hundred are not the same thing, so compare numbers as numbers.'] },
    { kind: 'flow', title: 'Switch: one question, many paths',
      nodes: [
        { kind: 'trigger', icon: 'headset', label: 'New ticket', sub: 'arrives', cue: 1 },
        { kind: 'logic', icon: 'split', label: 'Switch', sub: 'by category', cue: 2 },
        { kind: 'action', icon: 'file', label: 'Billing', sub: 'finance team', cue: 3 },
        { kind: 'action', icon: 'code', label: 'Technical', sub: 'engineers', cue: 3 },
        { kind: 'action', icon: 'user', label: 'Everything else', sub: 'front desk', cue: 4 },
      ],
      note: { text: 'Always give Switch a path for “everything else”.', cue: 5 },
      lines: ['When there are more than two answers, use the Switch node.', 'A ticket arrives.', 'Switch looks at its category.', 'Billing tickets go to finance, and technical tickets go to the engineers.', 'Anything else goes to the front desk.', 'Always give Switch a path for everything else, or unexpected items will quietly disappear.'] },
    { kind: 'example', title: 'In practice: orders at Nebula',
      scenario: 'Orders can be digital or physical, and from VIP or standard customers.',
      steps: [
        { time: 'Step 1', icon: 'split', text: 'IF: is the customer a VIP?', cue: 1 },
        { time: 'Step 2', icon: 'split', text: 'Switch: is the product digital or physical?', cue: 2 },
        { time: 'Digital', icon: 'mail', text: 'Email the download link', cue: 3 },
        { time: 'Physical', icon: 'send', text: 'Send the order to the warehouse', cue: 4 },
      ],
      result: { text: 'Two small decisions replace one long list of special cases.', cue: 5 },
      lines: ['Here is how Nebula uses both.', 'An IF node asks whether the customer is a VIP.', 'Then a Switch looks at the product type.', 'Digital orders get an email with the download link.', 'Physical orders go to the warehouse.', 'Two small decisions replace one long list of special cases.'] },
    { kind: 'cards', title: 'Branching, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['An expense arrives', 'IF over the limit', 'Ask a manager, or approve'], cue: 1 },
        { icon: 'user', title: 'HR', flow: ['An application arrives', 'Switch by department', 'Send to that hiring lead'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['A reading arrives', 'IF out of range', 'Raise a ticket, or just log it'], cue: 3 },
      ],
      lines: ['Branching appears wherever different cases need different handling.', 'In finance, an expense over the limit goes to a manager, and the rest are approved.', 'In human resources, applications are sent to the hiring lead for their department.', 'In a factory, a reading out of range raises a ticket, and the rest are just logged.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Filter drops items; IF and Switch route them', cue: 0 }, { text: 'IF has two paths, Switch has many', cue: 1 }, { text: 'A condition is a field, a test and a value', cue: 2 }, { text: 'Always handle “everything else”', cue: 3 }],
      lines: ['To sum up, Filter drops items, while IF and Switch route them.', 'IF has two paths, and Switch has many.', 'A condition is a field, a test and a value.', 'And always handle everything else.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'How is IF different from Filter?', options: ['IF drops the items that fail', 'IF sends items down a true path or a false path', 'IF can only test numbers'], correct: 1, explain: 'Filter has one way out; IF keeps both groups and routes them.', hint: 'How many ways out does each node have?' },
    { q: '10 items enter an IF node; 3 are true. Where do the other 7 go?', options: ['They are dropped', 'Down the false path', 'Back to the trigger'], correct: 1, explain: 'Every item leaves an IF node, by one path or the other.', hint: 'In the sorting office, is any parcel thrown away?' },
  ],
  endQuiz: [
    { q: 'Tickets have five possible categories. Which node fits best?', options: ['Filter', 'IF', 'Switch'], correct: 2, explain: 'Switch gives one path per answer, plus one for everything else.', hint: 'Two answers or many?' },
    { q: 'Why give Switch an “everything else” path?', options: ['It runs faster', 'So unexpected items are not silently lost', 'It is required before saving'], correct: 1, explain: 'Without it, an item that matches no rule goes nowhere.', hint: 'What happens to a ticket with a category nobody planned for?' },
  ],
})

const v32 = video({
  id: 'm3-2', title: 'Merging branches',
  slides: [
    { kind: 'title', icon: 'workflow', kicker: 'Module 3 · Video 2', title: 'Merging branches', sub: 'Bringing separate paths, and separate data, back together',
      lines: ['In the last lesson your workflow split into branches.', 'Now you will bring them back together.', 'The node for that is called Merge, and it has two quite different jobs.'] },
    { kind: 'bullets', title: 'Why merge at all?',
      lead: 'Branches often end in the same place.',
      bullets: [
        { icon: 'send', text: 'Every order, VIP or not, must be logged', cue: 1 },
        { icon: 'copy', text: 'Without a merge, the log node is built twice', cue: 2 },
        { icon: 'workflow', text: 'With a merge, both paths share one ending', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The benefit', text: 'One ending to maintain, instead of one per branch.', cue: 4 },
      lines: ['Why merge at all?', 'Because branches often end in the same place, for example every order must be logged.', 'Without a merge, you would build the log node twice, once on each branch.', 'With a merge, both paths share one ending.', 'That gives you one ending to maintain, instead of one per branch.'] },
    { kind: 'define', title: 'What does Merge do?', term: 'Merge',
      definition: 'A node with two inputs that turns them into one stream of items.',
      parts: [{ text: 'Two inputs', cue: 1 }, { text: 'One output', cue: 2 }, { text: 'A rule for combining', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'Two roads joining: either the lanes simply flow into one, or cars are paired up at a junction.' },
      lines: ['So what does Merge do?', 'It has two inputs.', 'It has one output.', 'And it has a rule for how the two are combined.', 'Picture two roads joining, where either the lanes simply flow into one, or the cars are paired up at a junction.'] },
    { kind: 'flow', title: 'Job 1 — Append: one after the other',
      nodes: [
        { kind: 'data', icon: 'send', label: 'VIP branch', sub: '3 items', cue: 1 },
        { kind: 'data', icon: 'mail', label: 'Standard branch', sub: '7 items', cue: 2 },
        { kind: 'logic', icon: 'workflow', label: 'Merge: Append', sub: '3 + 7', cue: 3 },
        { kind: 'action', icon: 'database', label: 'Log orders', sub: '10 items', cue: 4 },
      ],
      note: { text: 'Append simply stacks the items: 3 + 7 = 10.', cue: 5 },
      lines: ['The first job is called append.', 'The VIP branch delivers three items.', 'The standard branch delivers seven.', 'Merge in append mode stacks them, one group after the other.', 'So the log node receives all ten.', 'Append changes nothing inside the items, it only puts them in one stream.'] },
    { kind: 'table', title: 'Job 2 — Combine: match and join',
      columns: ['Orders', 'Customers', 'After Combine'],
      rows: [
        { cells: ['order 1 · maya@x.com', 'maya@x.com · VIP', 'order 1 · Maya · VIP'], cue: 1 },
        { cells: ['order 2 · tom@y.com', 'tom@y.com · standard', 'order 2 · Tom · standard'], cue: 2 },
        { cells: ['order 3 · sam@z.com', '(no match)', 'depends on your setting'], tone: 'bad', cue: 3 },
      ],
      note: { text: 'Combine pairs items that share a field, here the email.', cue: 4 },
      lines: ['The second job is called combine.', 'Here one input holds orders, the other holds customers, and Merge pairs them by email to give one richer item.', 'Tom’s order is paired with Tom’s customer record in the same way.', 'Sam has an order but no customer record, so you must decide whether to keep or drop him.', 'Combine pairs items that share a field, and in this case the field is the email.'] },
    { kind: 'compare', title: 'Append or Combine?',
      left: { label: 'Append', tone: 'info', cue: 1, points: ['Same kind of items on both sides', 'Result: more items', '3 + 7 = 10'] },
      right: { label: 'Combine', tone: 'info', cue: 3, points: ['Different data about the same thing', 'Result: richer items', '10 orders, each with its customer'] },
      lines: ['So how do you choose?', 'Use append when both sides hold the same kind of item.', 'The result is simply more items.', 'Use combine when the two sides hold different data about the same thing.', 'The result is the same number of items, but each one is richer.'] },
    { kind: 'bullets', title: 'Two things that go wrong',
      lead: 'Both are easy to spot if you count items.',
      bullets: [
        { icon: 'clock', text: 'Merge waits for both inputs before it runs', cue: 1 },
        { icon: 'x-circle', text: 'Unmatched items vanish in a combine', cue: 2 },
        { icon: 'pencil', text: 'Matching fails on untidy values', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The habit', text: 'Normalise the matching field first, then count items in and out.', cue: 4 },
      lines: ['Two things commonly go wrong.', 'Merge waits for both inputs, so if one branch never delivers, nothing comes out.', 'In a combine, items with no match can vanish, depending on the setting.', 'And matching fails on untidy values, such as an email with capital letters on one side only.', 'So normalise the matching field first, and then count the items in and out.'] },
    { kind: 'cards', title: 'Merging, everywhere',
      cards: [
        { icon: 'shop', title: 'Shop', flow: ['Orders from web and app', 'Append into one list', 'One daily report'], cue: 1 },
        { icon: 'headset', title: 'Support', flow: ['Tickets and customer plans', 'Combine by customer ID', 'Prioritise paying customers'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Readings and machine details', 'Combine by machine ID', 'A ticket that names the machine'], cue: 3 },
      ],
      lines: ['You will merge in almost every larger workflow.', 'A shop appends orders from the web and the app into one list for a daily report.', 'A support team combines tickets with customer plans, so paying customers come first.', 'A factory combines readings with machine details, so each ticket names the machine.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Merge joins two inputs into one stream', cue: 0 }, { text: 'Append stacks items; Combine pairs them', cue: 1 }, { text: 'Merge waits for both inputs', cue: 2 }, { text: 'Normalise the matching field, then count', cue: 3 }],
      lines: ['To sum up, Merge joins two inputs into one stream.', 'Append stacks items, and combine pairs them.', 'Merge waits for both inputs.', 'And normalise the matching field, then count.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'A VIP branch has 3 items and a standard branch has 7. What does Merge (Append) output?', options: ['3 items', '7 items', '10 items'], correct: 2, explain: 'Append stacks the two groups: 3 + 7 = 10.', hint: 'Append does not pair or drop anything.' },
    { q: 'You have orders in one input and customer records in the other. Which mode adds the customer to each order?', options: ['Append', 'Combine', 'Neither'], correct: 1, explain: 'Combine pairs items that share a field, such as the email.', hint: 'Do you want more items, or richer items?' },
  ],
  endQuiz: [
    { q: 'Nothing comes out of a Merge node. What is the first thing to check?', options: ['Whether both inputs received items', 'The workflow name', 'The trigger schedule'], correct: 0, explain: 'Merge waits for both inputs; if one branch delivers nothing, it has nothing to merge.', hint: 'How many inputs does Merge wait for?' },
    { q: 'A combine by email misses half the matches. What is the likely cause?', options: ['Too many items', 'The emails are written differently on the two sides', 'Merge only works on numbers'], correct: 1, explain: 'Matching compares values exactly, so normalise the field on both sides first.', hint: 'Remember “ Priya@X.com” and “priya@x.com”.' },
  ],
})

const v33 = video({
  id: 'm3-3', title: 'Talking to APIs',
  slides: [
    { kind: 'title', icon: 'webhook', kicker: 'Module 3 · Video 3', title: 'Talking to APIs', sub: 'Reaching any system with the HTTP Request node',
      lines: ['So far you have used ready-made nodes for apps such as Slack.', 'But many systems have no ready-made node.', 'In this lesson you will reach them anyway, through their API.'] },
    { kind: 'define', title: 'What is an API?', term: 'API',
      definition: 'The way one program asks another program for data, or asks it to do something.',
      parts: [{ text: 'You send a request', cue: 1 }, { text: 'To an address (URL)', cue: 2 }, { text: 'And get a response', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A waiter: you do not walk into the kitchen. You give an order in the agreed form, and a plate comes back.' },
      lines: ['An API is how one program talks to another.', 'You send a request.', 'You send it to an address, called a URL.', 'And you get a response back.', 'Think of a waiter, because you never walk into the kitchen, you give an order in the agreed form and a plate comes back.'] },
    { kind: 'bullets', title: 'The four parts of a request',
      lead: 'The HTTP Request node asks you for exactly these.',
      bullets: [
        { icon: 'send', text: 'Method: GET to read, POST to create', cue: 1 },
        { icon: 'search', text: 'URL: where the request goes', cue: 2 },
        { icon: 'user', text: 'Authentication: who you are', cue: 3 },
        { icon: 'boxes', text: 'Body: the data you send, if any', cue: 4 },
      ],
      aside: { icon: 'alert', label: 'Never', text: 'Type a password or key into the node. Store it once as a credential.', cue: 5 },
      lines: ['Every request has four parts, and the HTTP Request node asks you for each.', 'The method says what you want, where get means read and post means create.', 'The URL says where the request goes.', 'Authentication says who you are.', 'And the body carries the data you are sending, if there is any.', 'Never type a password or a key into the node itself, but store it once as a credential.'] },
    { kind: 'flow', title: 'A request, start to finish',
      nodes: [
        { kind: 'trigger', icon: 'clock', label: 'Every morning', sub: '9 AM', cue: 1 },
        { kind: 'data', icon: 'webhook', label: 'HTTP Request', sub: 'GET /customers', cue: 2 },
        { kind: 'data', icon: 'boxes', label: 'Response', sub: '50 customers', cue: 3 },
        { kind: 'action', icon: 'table', label: 'Update sheet', sub: '50 rows', cue: 4 },
      ],
      note: { text: 'The response becomes items, like any other data.', cue: 5 },
      lines: ['Here is a request from start to finish.', 'Every morning at nine the workflow starts.', 'The HTTP Request node asks the customer system for its customers.', 'The response comes back with fifty of them.', 'And the next node writes fifty rows to a sheet.', 'The response simply becomes items, just like any other data.'] },
    { kind: 'table', title: 'Reading the answer: status codes',
      columns: ['Code', 'Meaning', 'What to do'],
      rows: [
        { cells: ['200', 'It worked', 'Carry on'], cue: 1 },
        { cells: ['401', 'Not allowed', 'Check the credential'], tone: 'bad', cue: 2 },
        { cells: ['404', 'Not found', 'Check the URL'], tone: 'bad', cue: 3 },
        { cells: ['429', 'Too many requests', 'Slow down and retry'], tone: 'bad', cue: 4 },
      ],
      note: { text: 'The code tells you where the problem is before you read anything else.', cue: 5 },
      lines: ['Every response starts with a status code.', 'Two hundred means it worked.', 'Four oh one means you are not allowed, so check the credential.', 'Four oh four means not found, so check the URL.', 'Four two nine means too many requests, so slow down and retry.', 'The code tells you where the problem is before you read anything else.'] },
    { kind: 'compare', title: 'Pagination: the answer comes in pages',
      left: { label: 'One request', tone: 'bad', cue: 1, points: ['You ask for all customers', 'You get the first 50', 'The other 450 are missing'] },
      right: { label: 'Page by page', tone: 'ok', cue: 3, points: ['Ask for page 1, then page 2…', 'Stop when a page is empty', 'All 500 arrive'] },
      lines: ['There is one surprise that catches everybody, and it is called pagination.', 'You ask for all customers, but the system sends only the first fifty.', 'The other four hundred and fifty are silently missing.', 'The fix is to ask page by page, until a page comes back empty.', 'Then all five hundred arrive.'] },
    { kind: 'example', title: 'In practice: the CRM that said “slow down”',
      scenario: 'Nebula sends 500 customers to its CRM, one request each.',
      steps: [
        { time: 'First 100', icon: 'send', text: 'Requests succeed with code 200', cue: 1 },
        { time: 'Then', icon: 'alert', text: 'The CRM answers 429: too many requests', cue: 2 },
        { time: 'The fix', icon: 'clock', text: 'Send in batches, with a short wait between', cue: 3 },
        { time: 'Result', icon: 'database', text: 'All 500 are written, a little more slowly', cue: 4 },
      ],
      result: { text: 'A rate limit is not an error to fight. It is a speed to respect.', cue: 5 },
      lines: ['Here is a real case from Nebula, sending five hundred customers to its CRM.', 'The first hundred requests succeed.', 'Then the CRM answers with four two nine, too many requests.', 'The fix is to send in batches, with a short wait between them.', 'All five hundred are written, just a little more slowly.', 'A rate limit is not an error to fight, it is a speed to respect.'] },
    { kind: 'cards', title: 'APIs, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['Each morning', 'GET today’s exchange rates', 'Update the price list'], cue: 1 },
        { icon: 'shop', title: 'Shop', flow: ['An order is paid', 'POST it to the courier', 'Save the tracking number'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Every 5 minutes', 'GET the machine status', 'Alert if it is down'], cue: 3 },
      ],
      lines: ['With one node you can reach almost any system.', 'Finance fetches the exchange rates each morning and updates the price list.', 'A shop posts each paid order to the courier and saves the tracking number.', 'A factory asks for the machine status every five minutes and alerts if it is down.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'An API is a request to a URL, and a response back', cue: 0 }, { text: 'Method, URL, authentication, body', cue: 1 }, { text: 'Read the status code first', cue: 2 }, { text: 'Expect pages and rate limits', cue: 3 }],
      lines: ['To sum up, an API is a request to a URL, and a response back.', 'A request has a method, a URL, authentication and a body.', 'Read the status code first.', 'And expect pages and rate limits.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'Which method reads data without changing anything?', options: ['GET', 'POST', 'DELETE'], correct: 0, explain: 'GET reads; POST creates.', hint: 'One of them means “give me”.' },
    { q: 'Where should an API key be kept?', options: ['Typed into the node’s URL', 'In a stored credential', 'In the workflow name'], correct: 1, explain: 'Credentials are stored once and reused; they never sit in a node parameter.', hint: 'What happens when you share or export the workflow?' },
  ],
  endQuiz: [
    { q: 'A request returns 401. What do you check?', options: ['The URL', 'The credential', 'The number of items'], correct: 1, explain: '401 means not allowed — the authentication is missing or wrong.', hint: '401 is about who you are, not where you are going.' },
    { q: 'You asked for 500 customers and got exactly 50. Why?', options: ['The API is broken', 'The response is paginated', 'The workflow timed out'], correct: 1, explain: 'Most APIs answer in pages; ask page by page until one is empty.', hint: 'A suspiciously round number is a clue.' },
  ],
})

export default {
  id: 'm3', n: 3, lite: true,
  title: 'Logic, Branching & APIs',
  submodules: [
    { id: '3.1', title: 'Conditional logic', video: v31 },
    { id: '3.2', title: 'Merging branches', video: v32 },
    { id: '3.3', title: 'Talking to APIs', video: v33 },
  ],
  quiz: {
    passMark: 0.66,
    teachbackPrompt: 'Explain to a teammate when to use IF, when Switch, and when Merge.',
    questions: [
      { sub: '3.1', q: 'You need to keep both the passing and the failing items, on separate paths. Which node?', options: ['Filter', 'IF', 'Edit Fields'], correct: 1, explain: 'IF routes every item down a true or a false path; Filter would drop the failures.' },
      { sub: '3.1', q: 'A Switch has rules for “billing” and “technical”. A ticket arrives tagged “other”. What should exist?', options: ['Nothing — it will find a path', 'A path for everything else', 'A second trigger'], correct: 1, explain: 'Without a fallback path, an item matching no rule goes nowhere.' },
      { sub: '3.2', q: 'Two branches end with the same “log” step. What avoids building it twice?', options: ['A Merge node before one shared log node', 'Two triggers', 'A Filter on each branch'], correct: 0, explain: 'Merge the branches, then log once.' },
      { sub: '3.2', q: 'Combine by email returns far fewer items than expected. First check?', options: ['The workflow name', 'Whether the emails are normalised on both sides', 'The trigger'], correct: 1, explain: 'Matching is exact; untidy values on one side break the pairing.' },
      { sub: '3.3', q: 'An API answers 429. What does that mean?', options: ['Wrong URL', 'Too many requests — slow down', 'Wrong password'], correct: 1, explain: '429 is a rate limit: batch the requests and wait between them.' },
      { sub: '3.3', q: 'An HTTP Request returns only the first 50 of 500 records. What is missing?', options: ['Pagination', 'A Filter', 'A second credential'], correct: 0, explain: 'Request page after page until an empty page comes back.' },
    ],
  },
  reviews: [],
}
