import { video } from '../videos/prep.js'

/*
  Module 4 — Reliability, AI & Bigger Workflows (merged from the former modules 4 and 5).
  A video module: each lesson is a concept video with checks inside, then a module quiz.
*/
const v41 = video({
  id: 'm4-1', title: 'When things break',
  slides: [
    { kind: 'title', icon: 'alert', kicker: 'Module 4 · Video 1', title: 'When things break', sub: 'What a failure really is, and how a workflow can survive one',
      lines: ['Every workflow you build will fail one day.', 'That is not a sign of bad work, it is how connected systems behave.', 'In this lesson you will learn to make a workflow survive failure instead of stopping.'] },
    { kind: 'compare', title: 'Two kinds of failure',
      left: { label: 'Temporary', tone: 'info', cue: 1, points: ['The other system was busy', 'A network hiccup', 'Trying again will work'] },
      right: { label: 'Permanent', tone: 'bad', cue: 3, points: ['The data is wrong', 'The credential expired', 'Trying again will fail again'] },
      lines: ['Start by telling two kinds of failure apart.', 'A temporary failure means the other system was busy, or the network had a hiccup.', 'Trying again a moment later will usually work.', 'A permanent failure means the data is wrong, or a credential has expired.', 'Trying again will simply fail again.'] },
    { kind: 'flow', title: 'By default, one error stops everything',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Trigger', sub: '200 items', cue: 1 },
        { kind: 'data', icon: 'pencil', label: 'Edit Fields', sub: '200 items', cue: 2 },
        { kind: 'logic', icon: 'x-circle', label: 'CRM write', sub: 'fails on item 12', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Notify', sub: 'never runs', cue: 4 },
      ],
      note: { text: 'Item 12 failed, so items 13 to 200 were never tried.', cue: 5 },
      lines: ['Here is what happens with no protection.', 'Two hundred items leave the trigger.', 'They are cleaned as usual.', 'The CRM write fails on item twelve.', 'The whole run stops, and the last node never runs.', 'One bad item has blocked one hundred and eighty-eight good ones.'] },
    { kind: 'define', title: 'Setting 1: retry', term: 'Retry on fail',
      definition: 'A node setting that tries the same step again, after a short wait.',
      parts: [{ text: 'A number of tries', cue: 1 }, { text: 'A wait between them', cue: 2 }, { text: 'For temporary failures', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'Calling back when the line was busy: the same call, a minute later, usually gets through.' },
      lines: ['The first protection is a node setting called retry on fail.', 'You choose a number of tries.', 'You choose a wait between them.', 'And it is the right answer for temporary failures.', 'It is like calling back when the line was busy, because the same call a minute later usually gets through.'] },
    { kind: 'flow', title: 'Setting 2: continue, and keep the failures',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Trigger', sub: '200 items', cue: 1 },
        { kind: 'logic', icon: 'database', label: 'CRM write', sub: 'on error: continue', cue: 2 },
        { kind: 'action', icon: 'send', label: 'Success path', sub: '197 written', cue: 3 },
        { kind: 'action', icon: 'alert', label: 'Error path', sub: '3 to review', cue: 4 },
      ],
      note: { text: 'The good items finish. The failed ones are kept, not lost.', cue: 5 },
      lines: ['The second protection is for permanent failures.', 'Two hundred items arrive.', 'The CRM node is set to continue on error, and to send failures out of a separate error output.', 'One hundred and ninety-seven items are written.', 'Three go down the error path, to be reviewed.', 'The good items finish, and the failed ones are kept instead of lost.'] },
    { kind: 'table', title: 'Which setting, when?',
      columns: ['Situation', 'Setting', 'Why'],
      rows: [
        { cells: ['API busy or slow', 'Retry on fail', 'It will work in a moment'], cue: 1 },
        { cells: ['One row has bad data', 'Continue, with an error output', 'Do not block the rest'], cue: 2 },
        { cells: ['Credential expired', 'Stop, and alert a person', 'Nothing can succeed'], tone: 'bad', cue: 3 },
      ],
      note: { text: 'Match the response to the kind of failure.', cue: 4 },
      lines: ['So which setting do you use, and when?', 'If an API is busy or slow, retry, because it will work in a moment.', 'If one row has bad data, continue with an error output, so the rest are not blocked.', 'If a credential has expired, stop and alert a person, because nothing can succeed until it is fixed.', 'Match the response to the kind of failure.'] },
    { kind: 'example', title: 'In practice: the duplicate invoices',
      scenario: 'An invoice step timed out, was retried, and customers were charged twice.',
      steps: [
        { time: 'Try 1', icon: 'send', text: 'The invoice is created, but the reply is lost', cue: 1 },
        { time: 'Try 2', icon: 'copy', text: 'The retry creates the same invoice again', cue: 2 },
        { time: 'The fix', icon: 'search', text: 'Before creating, check whether it already exists', cue: 3 },
        { time: 'Now', icon: 'database', text: 'A retry finds the invoice and does nothing', cue: 4 },
      ],
      result: { text: 'A step that is retried must be safe to run twice.', cue: 5 },
      lines: ['Retries have one danger, and Nebula met it with invoices.', 'The first try created the invoice, but the reply was lost on the way back.', 'So the retry created the same invoice again.', 'The fix was to check whether the invoice already exists before creating it.', 'Now a retry finds the invoice and does nothing.', 'A step that is retried must be safe to run twice.'] },
    { kind: 'cards', title: 'Surviving failure, everywhere',
      cards: [
        { icon: 'shop', title: 'Shop', flow: ['An order arrives', 'Courier API is busy: retry', 'Label printed a minute late'], cue: 1 },
        { icon: 'file', title: 'Finance', flow: ['Expenses arrive', 'One has no amount: error path', 'The rest are booked'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Readings arrive', 'Database is down: stop and alert', 'An engineer is paged'], cue: 3 },
      ],
      lines: ['The same three responses work in every field.', 'A shop retries a busy courier, and the label is printed a minute late.', 'Finance sends the one bad expense down the error path, and books the rest.', 'A factory stops and pages an engineer when the database is down.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Failures are temporary or permanent', cue: 0 }, { text: 'Retry the temporary ones', cue: 1 }, { text: 'Continue past bad items, and keep them', cue: 2 }, { text: 'Anything retried must be safe to run twice', cue: 3 }],
      lines: ['To sum up, failures are either temporary or permanent.', 'Retry the temporary ones.', 'Continue past bad items, and keep them for review.', 'And anything that is retried must be safe to run twice.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'An API was busy for a few seconds. Which kind of failure is that?', options: ['Temporary', 'Permanent', 'Neither'], correct: 0, explain: 'It will work if tried again shortly — that is what retry is for.', hint: 'Would the same request work a minute later?' },
    { q: 'With no error settings, item 12 of 200 fails. What happens to items 13–200?', options: ['They are processed normally', 'They are never tried', 'They are retried'], correct: 1, explain: 'By default one error stops the whole execution.', hint: 'What does the workflow do by default when a node errors?' },
  ],
  endQuiz: [
    { q: 'One row in 200 has bad data. Which setting keeps the other 199 moving?', options: ['Retry on fail', 'Continue on error, with an error output', 'Stop the workflow'], correct: 1, explain: 'Retrying bad data fails again; continuing keeps the good items moving and saves the bad one.', hint: 'Will trying the same bad row again help?' },
    { q: 'Why can a retry be dangerous?', options: ['It slows the workflow', 'The step may already have happened, so it runs twice', 'It deletes the item'], correct: 1, explain: 'If the first try worked but the reply was lost, the retry repeats it — unless the step checks first.', hint: 'Think of the invoice that was created but never confirmed.' },
  ],
})

const v42 = video({
  id: 'm4-2', title: 'Error workflows',
  slides: [
    { kind: 'title', icon: 'bell-off', kicker: 'Module 4 · Video 2', title: 'Error workflows', sub: 'Making sure a person hears about a failure',
      lines: ['In the last lesson you made single nodes survive failure.', 'But some failures cannot be survived, and somebody has to be told.', 'In this lesson you will build the workflow that tells them.'] },
    { kind: 'compare', title: 'The silent failure',
      left: { label: 'Nobody is told', tone: 'bad', cue: 1, points: ['A workflow fails at 2 AM', 'It stays failed all night', 'A customer finds out first'] },
      right: { label: 'Somebody is told', tone: 'ok', cue: 3, points: ['A workflow fails at 2 AM', 'A message arrives at 2:01', 'It is fixed before breakfast'] },
      lines: ['The worst failure is the silent one.', 'A workflow fails at two in the morning, and nobody is told.', 'It stays failed all night, and a customer finds out first.', 'Now the same failure, but a message arrives one minute later.', 'It is fixed before breakfast, and no customer ever knows.'] },
    { kind: 'define', title: 'What is an error workflow?', term: 'Error workflow',
      definition: 'A separate workflow that runs automatically whenever another workflow fails.',
      parts: [{ text: 'Its own workflow', cue: 1 }, { text: 'Starts with an Error Trigger', cue: 2 }, { text: 'Runs when another one fails', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A smoke alarm: it does nothing all year, and on the one day it matters, it makes sure someone knows.' },
      lines: ['The tool for this is called an error workflow.', 'It is a workflow of its own.', 'It starts with a special node called the Error Trigger.', 'And it runs automatically whenever another workflow fails.', 'It is a smoke alarm, which does nothing all year, and on the one day it matters, makes sure someone knows.'] },
    { kind: 'flow', title: 'How the two workflows connect',
      nodes: [
        { kind: 'logic', icon: 'x-circle', label: 'Any workflow', sub: 'fails', cue: 1 },
        { kind: 'trigger', icon: 'alert', label: 'Error Trigger', sub: 'starts', cue: 2 },
        { kind: 'data', icon: 'pencil', label: 'Build message', sub: 'what and where', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Alert the team', sub: 'Slack or email', cue: 4 },
      ],
      note: { text: 'Set it once in each workflow’s settings: “Error workflow”.', cue: 5 },
      lines: ['Here is how the two connect.', 'Any workflow fails.', 'The Error Trigger in your error workflow starts.', 'A node builds a short message saying what failed and where.', 'And the team is alerted.', 'You connect them once, in each workflow’s settings, under error workflow.'] },
    { kind: 'bullets', title: 'What a good alert contains',
      lead: 'The Error Trigger hands you everything you need.',
      bullets: [
        { icon: 'workflow', text: 'Which workflow failed', cue: 1 },
        { icon: 'boxes', text: 'Which node, and its error message', cue: 2 },
        { icon: 'search', text: 'A link straight to the failed run', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The test', text: 'Could a colleague act on this message without asking you anything?', cue: 4 },
      lines: ['A good alert answers three questions.', 'Which workflow failed.', 'Which node failed, and with what error message.', 'And a link straight to the failed run.', 'The test is whether a colleague could act on the message without asking you anything.'] },
    { kind: 'define', title: 'Raising your own errors', term: 'Stop and Error',
      definition: 'A node that fails the workflow on purpose, with a message you write.',
      parts: [{ text: 'You decide when', cue: 1 }, { text: 'You write the message', cue: 2 }, { text: 'It triggers the alert', cue: 3 }],
      analogy: { label: 'Use it when', text: 'Nothing technically broke, but the result is wrong: zero rows arrived, or a total is negative.' },
      lines: ['Sometimes nothing technically breaks, but the result is still wrong.', 'For that there is a node called Stop and Error, where you decide when it fires.', 'You write the message yourself.', 'And it triggers the same alert as a real failure.', 'Use it when zero rows arrived, or when a total is negative.'] },
    { kind: 'example', title: 'In practice: the report with no data',
      scenario: 'A daily sales report ran “successfully” for a week, with zero sales in it.',
      steps: [
        { time: 'Cause', icon: 'user', text: 'A credential lost access; the API returned nothing', cue: 1 },
        { time: 'Effect', icon: 'mail', text: 'An empty report was emailed every morning', cue: 2 },
        { time: 'The fix', icon: 'split', text: 'IF there are zero rows, Stop and Error', cue: 3 },
        { time: 'Now', icon: 'alert', text: 'The error workflow alerts the team the same day', cue: 4 },
      ],
      result: { text: 'Decide what “wrong” looks like, and make it fail loudly.', cue: 5 },
      lines: ['Here is why that matters.', 'A credential lost access, and the API quietly returned nothing.', 'So an empty report was emailed every morning for a week.', 'The fix was an IF node that checks for zero rows and then uses Stop and Error.', 'Now the error workflow alerts the team the same day.', 'Decide what wrong looks like, and make it fail loudly.'] },
    { kind: 'cards', title: 'Error workflows, everywhere',
      cards: [
        { icon: 'shop', title: 'Shop', flow: ['The order sync fails', 'Error workflow starts', 'The on-call person is messaged'], cue: 1 },
        { icon: 'file', title: 'Finance', flow: ['Invoicing fails', 'Error workflow starts', 'A ticket is opened for finance'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['The sensor import fails', 'Error workflow starts', 'The shift lead is paged'], cue: 3 },
      ],
      lines: ['One error workflow can serve every workflow you own.', 'In a shop, a failed order sync messages the on-call person.', 'In finance, failed invoicing opens a ticket.', 'In a factory, a failed sensor import pages the shift lead.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'A failure nobody hears about is the worst kind', cue: 0 }, { text: 'An error workflow starts with an Error Trigger', cue: 1 }, { text: 'Say what failed, where, and link to the run', cue: 2 }, { text: 'Use Stop and Error when the result is wrong', cue: 3 }],
      lines: ['To sum up, a failure nobody hears about is the worst kind.', 'An error workflow starts with an Error Trigger.', 'A good alert says what failed and where, and links to the run.', 'And use Stop and Error when nothing broke but the result is wrong.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'What starts an error workflow?', options: ['A schedule', 'The Error Trigger, when another workflow fails', 'A person clicking run'], correct: 1, explain: 'It runs automatically whenever a workflow that points to it fails.', hint: 'Think of the smoke alarm: what sets it off?' },
    { q: 'Which is most useful in an alert?', options: ['The workflow, the node, the error and a link to the run', 'The date only', 'A list of every node'], correct: 0, explain: 'A colleague should be able to act on it without asking anything.', hint: 'What would you need at 2 AM to start fixing it?' },
  ],
  endQuiz: [
    { q: 'A report runs green every day but contains zero rows. How do you get alerted?', options: ['Wait for a real error', 'Check for zero rows and use Stop and Error', 'Add more retries'], correct: 1, explain: 'Nothing technically failed, so you raise the error yourself.', hint: 'The workflow thinks everything is fine — who has to say otherwise?' },
    { q: 'How many error workflows do ten workflows need?', options: ['Ten', 'One, shared by all of them', 'None'], correct: 1, explain: 'Each workflow points to the same error workflow in its settings.', hint: 'How many smoke alarms per building, not per room?' },
  ],
})

const v43 = video({
  id: 'm4-3', title: 'AI in the loop',
  slides: [
    { kind: 'title', icon: 'boxes', kicker: 'Module 4 · Video 3', title: 'AI in the loop', sub: 'Using a language model as one careful step in a workflow',
      lines: ['Some jobs cannot be done with rules, because they need reading and judgement.', 'For those you can add an AI model as one step in a workflow.', 'In this lesson you will learn where that helps, and how to keep it under control.'] },
    { kind: 'compare', title: 'Rules, or a model?',
      left: { label: 'Use rules when', tone: 'info', cue: 1, points: ['The answer is in a field', 'The test is exact', '“total over 200”'] },
      right: { label: 'Use a model when', tone: 'info', cue: 3, points: ['The answer is in free text', 'It needs reading', '“is this customer angry?”'] },
      lines: ['First, when do you need a model at all?', 'Use rules when the answer is in a field, and the test is exact.', 'Whether a total is over two hundred needs no intelligence.', 'Use a model when the answer is buried in free text.', 'Whether a customer is angry is something a rule cannot read.'] },
    { kind: 'bullets', title: 'Three jobs a model does well',
      lead: 'Each takes free text in and gives structured data out.',
      bullets: [
        { icon: 'split', text: 'Classify: billing, technical or other', cue: 1 },
        { icon: 'search', text: 'Extract: the order number from an email', cue: 2 },
        { icon: 'pencil', text: 'Summarise: a long thread in two lines', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'Notice', text: 'The output is a field your next node can test, not a paragraph.', cue: 4 },
      lines: ['There are three jobs a model does well inside a workflow.', 'It can classify, for example billing, technical or other.', 'It can extract, for example the order number from an email.', 'And it can summarise a long thread into two lines.', 'In each case the output is a field your next node can test, not a paragraph.'] },
    { kind: 'flow', title: 'A model as one step',
      nodes: [
        { kind: 'trigger', icon: 'headset', label: 'New ticket', sub: 'free text', cue: 1 },
        { kind: 'data', icon: 'boxes', label: 'AI: classify', sub: 'category + urgency', cue: 2 },
        { kind: 'logic', icon: 'split', label: 'Switch', sub: 'by category', cue: 3 },
        { kind: 'action', icon: 'send', label: 'Assign', sub: 'right team', cue: 4 },
      ],
      note: { text: 'The model reads. Ordinary nodes decide and act.', cue: 5 },
      lines: ['Here is a model used as one step.', 'A ticket arrives as free text.', 'The AI node reads it and returns a category and an urgency.', 'A Switch routes it by category.', 'And the ticket is assigned to the right team.', 'The model reads, and ordinary nodes decide and act.'] },
    { kind: 'code', title: 'The prompt is part of your workflow',
      lead: 'A good prompt says what to return, and in what form.',
      rows: [
        { code: 'Classify this ticket: {{ $json.text }}', out: 'the task, with the item’s text', cue: 1 },
        { code: 'Answer with one of: billing, technical, other', out: 'only allowed answers', cue: 2 },
        { code: 'If unsure, answer: other', out: 'a safe way out', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'Why so strict', text: 'The next node tests the answer. It must be one of the values you expect.', cue: 4 },
      lines: ['The instruction you give the model is called a prompt, and it is part of your workflow.', 'It states the task, and uses an expression to include the text of the item.', 'It lists the only answers that are allowed.', 'And it gives the model a safe way out when it is unsure.', 'It is strict because the next node tests the answer, which must be one of the values you expect.'] },
    { kind: 'bullets', title: 'A model can be wrong — plan for it',
      lead: 'Treat its output like data from an outside system: check it.',
      bullets: [
        { icon: 'filter', text: 'Validate: is the answer one of the allowed values?', cue: 1 },
        { icon: 'user', text: 'Human approval before anything irreversible', cue: 2 },
        { icon: 'eye', text: 'Log what it decided, so you can review', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'The rule', text: 'A model may suggest. A person approves refunds, deletions and messages to customers.', cue: 4 },
      lines: ['A model can be wrong, so treat its output like data from an outside system.', 'Validate it, by checking the answer is one of the allowed values.', 'Put a human approval step before anything that cannot be undone.', 'And log what it decided, so you can review it later.', 'The rule is that a model may suggest, but a person approves refunds, deletions and messages to customers.'] },
    { kind: 'example', title: 'In practice: 200 tickets a day',
      scenario: 'Nebula’s support inbox gets 200 tickets a day, all free text.',
      steps: [
        { time: 'Read', icon: 'boxes', text: 'The model returns category and urgency', cue: 1 },
        { time: 'Check', icon: 'filter', text: 'Unexpected answers go to a person', cue: 2 },
        { time: 'Route', icon: 'split', text: 'Routine tickets are assigned automatically', cue: 3 },
        { time: 'Approve', icon: 'user', text: 'Refund requests wait for a human', cue: 4 },
      ],
      result: { text: '180 tickets routed in seconds; 20 handled by people, on purpose.', cue: 5 },
      lines: ['Here is the whole pattern at Nebula, with two hundred tickets a day.', 'The model reads each ticket and returns a category and an urgency.', 'Unexpected answers go straight to a person.', 'Routine tickets are assigned automatically.', 'Refund requests wait for a human to approve.', 'One hundred and eighty are routed in seconds, and twenty are handled by people, on purpose.'] },
    { kind: 'cards', title: 'AI in the loop, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['An invoice PDF arrives', 'Extract supplier and amount', 'A person approves payment'], cue: 1 },
        { icon: 'user', title: 'HR', flow: ['An application arrives', 'Summarise the experience', 'A recruiter decides'], cue: 2 },
        { icon: 'shop', title: 'Shop', flow: ['A review is posted', 'Classify it as praise or complaint', 'Complaints go to a person'], cue: 3 },
      ],
      lines: ['The same pattern works wherever people read text all day.', 'In finance, a model extracts the supplier and amount, and a person approves the payment.', 'In human resources, a model summarises an application, and a recruiter decides.', 'In a shop, a model sorts reviews, and the complaints go to a person.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Use a model for reading, rules for exact tests', cue: 0 }, { text: 'Ask for a fixed set of answers', cue: 1 }, { text: 'Validate the output before using it', cue: 2 }, { text: 'A person approves what cannot be undone', cue: 3 }],
      lines: ['To sum up, use a model for reading, and rules for exact tests.', 'Ask for a fixed set of answers.', 'Validate the output before using it.', 'And a person approves anything that cannot be undone.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'Which job needs a model rather than a rule?', options: ['Is the total over 200?', 'Is this free-text message a complaint?', 'Is the email field empty?'], correct: 1, explain: 'A rule can test a field exactly; reading meaning from free text needs a model.', hint: 'Which one cannot be answered by comparing a field with a value?' },
    { q: 'Why tell the model to answer with one of a fixed list?', options: ['It is cheaper', 'So the next node can test the answer reliably', 'Models cannot write sentences'], correct: 1, explain: 'A Switch can only route answers it expects.', hint: 'What comes straight after the AI node?' },
  ],
  endQuiz: [
    { q: 'The model returns “maybe billing?”. What should the workflow do?', options: ['Route it to billing', 'Send it to a person, because it is not an allowed answer', 'Run the model again until it changes'], correct: 1, explain: 'Validate the output; anything unexpected goes to a human.', hint: 'Is that one of the values you asked for?' },
    { q: 'Which action should always wait for human approval?', options: ['Adding a label to a ticket', 'Issuing a refund', 'Writing a log line'], correct: 1, explain: 'A model may suggest; a person approves what cannot be undone.', hint: 'Which of these is hard to take back?' },
  ],
})

const v44 = video({
  id: 'm4-4', title: 'Sub-workflows',
  slides: [
    { kind: 'title', icon: 'workflow', kicker: 'Module 4 · Video 4', title: 'Sub-workflows', sub: 'Building once, and reusing everywhere',
      lines: ['As your automations grow, two problems appear.', 'Workflows become too large to read, and the same steps get built again and again.', 'In this lesson you will solve both with sub-workflows.'] },
    { kind: 'compare', title: 'Copying, or reusing',
      left: { label: 'Copy the steps', tone: 'bad', cue: 1, points: ['The cleaning steps exist in 5 workflows', 'A rule changes', 'You fix it 5 times, and miss one'] },
      right: { label: 'Reuse one sub-workflow', tone: 'ok', cue: 3, points: ['The cleaning steps exist once', 'A rule changes', 'You fix it once, everywhere'] },
      lines: ['Imagine your email cleaning steps are needed in five workflows.', 'If you copy them, they exist five times.', 'When a rule changes, you fix it five times, and probably miss one.', 'If you reuse one sub-workflow, the steps exist once.', 'When a rule changes, you fix it once, and it is fixed everywhere.'] },
    { kind: 'define', title: 'What is a sub-workflow?', term: 'Sub-workflow',
      definition: 'A workflow that is started by another workflow, does one job, and hands its result back.',
      parts: [{ text: 'Called by a parent', cue: 1 }, { text: 'Does one job', cue: 2 }, { text: 'Returns its result', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A specialist you send work to: you hand over a file, they do their part, and the file comes back.' },
      lines: ['So what is a sub-workflow?', 'It is a workflow that is called by another one, which we call the parent.', 'It does one job.', 'And it returns its result to the parent.', 'Think of a specialist you send work to, where you hand over a file, they do their part, and the file comes back.'] },
    { kind: 'flow', title: 'How the call works',
      nodes: [
        { kind: 'trigger', icon: 'table', label: 'Parent', sub: '500 items', cue: 1 },
        { kind: 'data', icon: 'workflow', label: 'Execute Sub-workflow', sub: 'sends 500', cue: 2 },
        { kind: 'logic', icon: 'pencil', label: 'Sub-workflow', sub: 'cleans them', cue: 3 },
        { kind: 'action', icon: 'database', label: 'Parent continues', sub: '462 back', cue: 4 },
      ],
      note: { text: 'The parent waits, then carries on with what came back.', cue: 5 },
      lines: ['Here is how the call works.', 'The parent workflow holds five hundred items.', 'A node called Execute Sub-workflow sends them across.', 'The sub-workflow cleans them, starting from its own special trigger.', 'And the parent continues with the four hundred and sixty-two that came back.', 'The parent waits, then carries on with whatever was returned.'] },
    { kind: 'bullets', title: 'What makes a good sub-workflow',
      lead: 'Pull a group of nodes out when it has these three properties.',
      bullets: [
        { icon: 'boxes', text: 'One clear job: “clean customer records”', cue: 1 },
        { icon: 'download', text: 'A clear input: which fields it expects', cue: 2 },
        { icon: 'send', text: 'A clear output: which fields it returns', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'A useful test', text: 'If you can name it in three words, it is probably one job.', cue: 4 },
      lines: ['What should you pull out into a sub-workflow?', 'Something with one clear job, such as clean customer records.', 'Something with a clear input, meaning the fields it expects.', 'And something with a clear output, meaning the fields it returns.', 'A useful test is that if you can name it in three words, it is probably one job.'] },
    { kind: 'compare', title: 'One giant workflow, or small parts',
      left: { label: 'One workflow, 60 nodes', tone: 'bad', cue: 1, points: ['Hard to read', 'One change risks everything', 'Tested only as a whole'] },
      right: { label: 'A parent and 4 sub-workflows', tone: 'ok', cue: 3, points: ['Each part fits on one screen', 'A change stays in its part', 'Each part is tested alone'] },
      lines: ['Reuse is only half the benefit.', 'A single workflow with sixty nodes is hard to read, and one change risks everything.', 'It can only be tested as a whole.', 'Split into a parent and four sub-workflows, each part fits on one screen.', 'And each part can be tested alone, with its own sample data.'] },
    { kind: 'example', title: 'In practice: one cleaner, three users',
      scenario: 'Nebula cleans customer data in three places: sign-ups, imports and the CRM sync.',
      steps: [
        { time: 'Before', icon: 'copy', text: 'Three copies of the cleaning steps, slightly different', cue: 1 },
        { time: 'Extract', icon: 'workflow', text: 'One “Clean customers” sub-workflow', cue: 2 },
        { time: 'Call', icon: 'send', text: 'All three workflows call it', cue: 3 },
        { time: 'Later', icon: 'pencil', text: 'A new date format is handled in one place', cue: 4 },
      ],
      result: { text: 'Three workflows got shorter, and all three now clean data the same way.', cue: 5 },
      lines: ['Here is the idea at Nebula, where customer data is cleaned in three places.', 'Before, there were three copies of the cleaning steps, each slightly different.', 'They were pulled out into one sub-workflow called clean customers.', 'Now all three workflows call it.', 'Later, when a new date format appeared, it was handled in one place.', 'Three workflows got shorter, and all three now clean data the same way.'] },
    { kind: 'cards', title: 'Sub-workflows, everywhere',
      cards: [
        { icon: 'send', title: 'Notify', flow: ['Any workflow needs to alert', 'Call “Notify the team”', 'One place sets the channel'], cue: 1 },
        { icon: 'search', title: 'Look up', flow: ['An order needs its customer', 'Call “Find customer”', 'The customer comes back'], cue: 2 },
        { icon: 'filter', title: 'Validate', flow: ['A record arrives', 'Call “Check address”', 'Valid, or a reason why not'], cue: 3 },
      ],
      lines: ['Three kinds of sub-workflow turn up in almost every team.', 'A notify sub-workflow, so one place decides which channel alerts go to.', 'A look-up sub-workflow, which takes an order and returns its customer.', 'And a validate sub-workflow, which returns valid, or a reason why not.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'A sub-workflow does one job for a parent', cue: 0 }, { text: 'Build once, reuse everywhere', cue: 1 }, { text: 'Give it a clear input and output', cue: 2 }, { text: 'Small parts are easier to read and test', cue: 3 }],
      lines: ['To sum up, a sub-workflow does one job for a parent workflow.', 'Build it once, and reuse it everywhere.', 'Give it a clear input and a clear output.', 'And remember that small parts are easier to read and to test.'] },
  ],
  quizAfter: 4,
  midQuiz: [
    { q: 'The same cleaning steps are copied into five workflows. What is the main risk?', options: ['They run more slowly', 'A change must be made five times, and one gets missed', 'They use more credentials'], correct: 1, explain: 'Copies drift apart; one shared sub-workflow is fixed once.', hint: 'What happens the day a rule changes?' },
    { q: 'What does the parent workflow do while the sub-workflow runs?', options: ['It carries on without waiting', 'It waits, then continues with what came back', 'It stops for good'], correct: 1, explain: 'The Execute Sub-workflow node hands over the items and receives the result.', hint: 'Think of the specialist returning the file.' },
  ],
  endQuiz: [
    { q: 'Which group of nodes is the best candidate for a sub-workflow?', options: ['Steps that do one clear job used in several workflows', 'The trigger', 'Any three nodes in a row'], correct: 0, explain: 'One job, a clear input and a clear output — and needed in more than one place.', hint: 'Could you name it in three words?' },
    { q: 'Besides reuse, what does splitting a 60-node workflow give you?', options: ['Fewer items', 'Parts that can be read and tested on their own', 'No need for a trigger'], correct: 1, explain: 'Each part fits on a screen and can be tested alone.', hint: 'What is hard about changing one node among sixty?' },
  ],
})

const v45 = video({
  id: 'm4-5', title: 'The Code node',
  slides: [
    { kind: 'title', icon: 'code', kicker: 'Module 4 · Video 5', title: 'The Code node', sub: 'A few lines of your own, for when no node fits',
      lines: ['Almost everything can be built from ready-made nodes.', 'Almost, but not quite everything.', 'In this lesson you will meet the Code node, and learn when to use it and when not to.'] },
    { kind: 'compare', title: 'A node, or code?',
      left: { label: 'Use a node when', tone: 'ok', cue: 1, points: ['One exists for the job', 'A teammate should read it at a glance', 'Rename, filter, merge, sort'] },
      right: { label: 'Use code when', tone: 'info', cue: 3, points: ['No node does it', 'It would take ten nodes', 'A custom calculation or reshaping'] },
      lines: ['The first question is always whether you need code at all.', 'Use a node when one exists for the job, because a teammate can read it at a glance.', 'Renaming, filtering, merging and sorting all have nodes.', 'Use code when no node does the job, or when it would take ten nodes.', 'A custom calculation or an unusual reshaping are good examples.'] },
    { kind: 'define', title: 'What is the Code node?', term: 'Code node',
      definition: 'A node that runs a few lines of JavaScript on the items passing through.',
      parts: [{ text: 'Receives items', cue: 1 }, { text: 'Runs your lines', cue: 2 }, { text: 'Must return items', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A blank station on the conveyor belt: parcels arrive, you decide what happens, parcels must leave.' },
      lines: ['The Code node runs a few lines of JavaScript.', 'It receives items like any other node.', 'It runs the lines you wrote.', 'And it must return items, so the next node has something to work with.', 'Think of a blank station on the conveyor belt, where parcels arrive, you decide what happens, and parcels must leave.'] },
    { kind: 'table', title: 'Two ways it can run',
      columns: ['Mode', 'Your code sees', 'Good for'],
      rows: [
        { cells: ['Run once for each item', 'One item at a time', 'Changing every item'], cue: 1 },
        { cells: ['Run once for all items', 'The whole list', 'Totals, sorting, grouping'], cue: 2 },
      ],
      note: { text: 'Pick the mode first; it decides how you write the code.', cue: 3 },
      lines: ['The Code node can run in two ways.', 'Run once for each item means your code sees one item at a time, which is good for changing every item.', 'Run once for all items means your code sees the whole list, which is good for totals, sorting and grouping.', 'Pick the mode first, because it decides how you write the code.'] },
    { kind: 'code', title: 'For each item: add a field',
      lead: 'Mode: run once for each item.',
      rows: [
        { code: 'const total = $json.price * $json.qty', out: 'work out a value', cue: 1 },
        { code: '$json.total = total', out: 'add it to the item', cue: 2 },
        { code: 'return $json', out: 'hand the item back', cue: 3 },
      ],
      aside: { icon: 'alert', label: 'Do not forget', text: 'If nothing is returned, nothing reaches the next node.', cue: 4 },
      lines: ['Here is the simplest useful example, in the mode for each item.', 'The first line works out a total from the price and the quantity.', 'The second adds that total to the item as a new field.', 'The third hands the item back.', 'Do not forget that last line, because if nothing is returned, nothing reaches the next node.'] },
    { kind: 'code', title: 'For all items: one summary',
      lead: 'Mode: run once for all items.',
      rows: [
        { code: 'const items = $input.all()', out: 'the whole list', cue: 1 },
        { code: 'const sum = items.reduce(…)', out: 'add up every total', cue: 2 },
        { code: 'return [{ json: { sum } }]', out: 'one item comes out', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'Notice', text: '500 items in, 1 item out. Count items after a Code node, as after any other.', cue: 4 },
      lines: ['And here is the other mode, working on all items at once.', 'The first line takes the whole list.', 'The second adds up every total.', 'The third returns a single item holding the sum.', 'Notice that five hundred items went in and one came out, so count items after a Code node as you would after any other.'] },
    { kind: 'bullets', title: 'Keeping code under control',
      lead: 'Code is powerful, and harder for the next person to read.',
      bullets: [
        { icon: 'pencil', text: 'Name the node after what it does', cue: 1 },
        { icon: 'boxes', text: 'Keep it short: one job per Code node', cue: 2 },
        { icon: 'x-circle', text: 'No passwords or keys in the code', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The test', text: 'If a node exists for it, use the node.', cue: 4 },
      lines: ['Code is powerful, but it is harder for the next person to read.', 'So name the node after what it does.', 'Keep it short, with one job in each Code node.', 'And never put passwords or keys in the code.', 'The final test is simple, which is that if a node exists for the job, use the node.'] },
    { kind: 'cards', title: 'Good uses of the Code node',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['Invoices arrive', 'Code: tax by country rules', 'Save the totals'], cue: 1 },
        { icon: 'shop', title: 'Shop', flow: ['Orders arrive', 'Code: group lines by order', 'One item per order'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['Readings arrive', 'Code: average of the last ten', 'Alert on a jump'], cue: 3 },
      ],
      lines: ['Here are three good uses.', 'In finance, a tax calculation with rules that differ by country.', 'In a shop, grouping order lines so that each order becomes one item.', 'In a factory, an average of the last ten readings, to alert on a sudden jump.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'Use a node if one exists; code if none does', cue: 0 }, { text: 'Choose the mode: each item, or all items', cue: 1 }, { text: 'Always return items', cue: 2 }, { text: 'Short, named, and free of secrets', cue: 3 }],
      lines: ['To sum up, use a node if one exists, and code if none does.', 'Choose the mode, which is each item or all items.', 'Always return items.', 'And keep your code short, named, and free of secrets.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'When is the Code node the right choice?', options: ['Whenever possible', 'When no node does the job, or it would take many nodes', 'Never'], correct: 1, explain: 'Nodes are easier to read; code is for what they cannot do.', hint: 'Which is easier for a teammate to read at a glance?' },
    { q: 'You need one grand total across 500 items. Which mode?', options: ['Run once for each item', 'Run once for all items', 'Either gives the same result'], correct: 1, explain: 'A total needs the whole list at once.', hint: 'Does your code need to see one item, or all of them?' },
  ],
  endQuiz: [
    { q: 'The node after a Code node receives nothing. Most likely cause?', options: ['The code did not return any items', 'The trigger is wrong', 'There are too many items'], correct: 0, explain: 'A Code node must return items for the next node.', hint: 'What is the last line of the code?' },
    { q: 'Where should an API key used by your code live?', options: ['In the code', 'In a credential, not in the code', 'In a comment'], correct: 1, explain: 'Secrets never go in code or node parameters.', hint: 'Who can read the code when the workflow is shared?' },
  ],
})

const v46 = video({
  id: 'm4-6', title: 'Files and binary data',
  slides: [
    { kind: 'title', icon: 'file', kicker: 'Module 4 · Video 6', title: 'Files and binary data', sub: 'PDFs, spreadsheets and attachments inside a workflow',
      lines: ['So far every item has been made of fields.', 'But real work is full of files, such as invoices, spreadsheets and photos.', 'In this lesson you will learn how a workflow carries files, and how to get data out of them.'] },
    { kind: 'compare', title: 'Two kinds of data in one item',
      left: { label: 'JSON data', tone: 'info', cue: 1, points: ['Fields with names', 'name, email, total', 'Nodes can read it directly'] },
      right: { label: 'Binary data', tone: 'info', cue: 3, points: ['A whole file', 'invoice.pdf, photo.jpg', 'Carried along, not read'] },
      lines: ['An item can actually carry two kinds of data.', 'The first is the kind you know, with named fields such as name, email and total.', 'Nodes can read it directly.', 'The second is binary data, which is a whole file such as a PDF or a photo.', 'The file is carried along with the item, but nodes cannot read inside it.'] },
    { kind: 'define', title: 'What is binary data?', term: 'Binary data',
      definition: 'A file attached to an item: carried through the workflow, but not readable as fields.',
      parts: [{ text: 'Travels with the item', cue: 1 }, { text: 'Has a name and a type', cue: 2 }, { text: 'Must be extracted to be read', cue: 3 }],
      analogy: { label: 'Think of it as', text: 'A sealed envelope clipped to a form: it goes wherever the form goes, but you must open it to read it.' },
      lines: ['Here is the definition.', 'Binary data is a file that travels with the item.', 'It has a file name and a type.', 'And it must be extracted before its contents can be read.', 'Picture a sealed envelope clipped to a form, which goes wherever the form goes, but must be opened to be read.'] },
    { kind: 'flow', title: 'Getting data out of a file',
      nodes: [
        { kind: 'trigger', icon: 'mail', label: 'Email arrives', sub: 'orders.csv attached', cue: 1 },
        { kind: 'data', icon: 'file', label: 'Extract from File', sub: 'CSV → rows', cue: 2 },
        { kind: 'logic', icon: 'filter', label: 'Filter', sub: 'valid rows', cue: 3 },
        { kind: 'action', icon: 'database', label: 'Save orders', sub: '120 items', cue: 4 },
      ],
      note: { text: 'One file went in; 120 ordinary items came out.', cue: 5 },
      lines: ['Here is how you open the envelope.', 'An email arrives with a spreadsheet file attached.', 'A node called Extract from File turns the file into rows.', 'From here on everything is familiar, so a Filter keeps the valid rows.', 'And the orders are saved.', 'One file went in, and one hundred and twenty ordinary items came out.'] },
    { kind: 'table', title: 'The file nodes you will use',
      columns: ['Node', 'What it does', 'Example'],
      rows: [
        { cells: ['Extract from File', 'File → items', 'CSV, Excel or PDF text'], cue: 1 },
        { cells: ['Convert to File', 'Items → file', 'A report as CSV'], cue: 2 },
        { cells: ['Read / Write Files', 'Load or save a file', 'Keep a copy on disk'], cue: 3 },
      ],
      note: { text: 'Extract to work with the data; convert to send it on.', cue: 4 },
      lines: ['Three nodes cover most file work.', 'Extract from File turns a file into items, and it handles CSV, Excel and the text of a PDF.', 'Convert to File does the opposite, turning items into a file such as a report.', 'And the read and write nodes load or save a file.', 'Extract when you want to work with the data, and convert when you want to send it on.'] },
    { kind: 'flow', title: 'Building a file to send',
      nodes: [
        { kind: 'trigger', icon: 'clock', label: 'Every Monday', sub: '8 AM', cue: 1 },
        { kind: 'data', icon: 'database', label: 'Get sales', sub: '340 items', cue: 2 },
        { kind: 'data', icon: 'file', label: 'Convert to File', sub: 'sales.csv', cue: 3 },
        { kind: 'action', icon: 'mail', label: 'Email', sub: 'file attached', cue: 4 },
      ],
      note: { text: '340 items went in; one item with one file came out.', cue: 5 },
      lines: ['Now the other direction.', 'Every Monday at eight the workflow starts.', 'It fetches three hundred and forty sales records.', 'Convert to File turns them into one spreadsheet file.', 'And an email goes out with the file attached.', 'Three hundred and forty items went in, and one item with one file came out.'] },
    { kind: 'bullets', title: 'Three things that go wrong with files',
      lead: 'Each has a simple check.',
      bullets: [
        { icon: 'x-circle', text: 'A node drops the file: check it is still attached', cue: 1 },
        { icon: 'search', text: 'The wrong file type arrives: test the type first', cue: 2 },
        { icon: 'alert', text: 'A scanned PDF has no text to extract', cue: 3 },
      ],
      aside: { icon: 'eye', label: 'The habit', text: 'After each node, look for the file as well as the fields.', cue: 4 },
      lines: ['Three things commonly go wrong with files.', 'A node in the middle drops the file, so check that it is still attached.', 'The wrong file type arrives, so test the type before extracting.', 'And a scanned PDF is only a picture, with no text to extract.', 'So after each node, look for the file as well as the fields.'] },
    { kind: 'cards', title: 'Files, everywhere',
      cards: [
        { icon: 'file', title: 'Finance', flow: ['An invoice PDF arrives', 'Extract its text', 'Save amount and supplier'], cue: 1 },
        { icon: 'user', title: 'HR', flow: ['A CV is uploaded', 'Store the file', 'Notify the recruiter'], cue: 2 },
        { icon: 'factory', title: 'Factory', flow: ['The shift ends', 'Convert readings to a CSV', 'Email it to the manager'], cue: 3 },
      ],
      lines: ['Files appear in every department.', 'Finance extracts the text of an invoice and saves the amount and the supplier.', 'Human resources stores an uploaded CV and notifies the recruiter.', 'A factory converts the readings of a shift into a file and emails it to the manager.'] },
    { kind: 'recap', title: 'What to take away',
      points: [{ text: 'An item can carry fields and a file', cue: 0 }, { text: 'Extract from File turns a file into items', cue: 1 }, { text: 'Convert to File turns items into a file', cue: 2 }, { text: 'Check the file is still there after each node', cue: 3 }],
      lines: ['To sum up, an item can carry fields and a file.', 'Extract from File turns a file into items.', 'Convert to File turns items into a file.', 'And check that the file is still there after each node.'] },
  ],
  quizAfter: 3,
  midQuiz: [
    { q: 'What is binary data?', options: ['A field with a number in it', 'A file attached to an item', 'An error message'], correct: 1, explain: 'It is a whole file — a PDF, a spreadsheet, a photo — carried with the item.', hint: 'Think of the sealed envelope clipped to the form.' },
    { q: 'A CSV file arrives by email. Which node turns it into rows?', options: ['Convert to File', 'Extract from File', 'Merge'], correct: 1, explain: 'Extract from File goes from a file to items.', hint: 'You want to get data out of the file.' },
  ],
  endQuiz: [
    { q: '340 items go into Convert to File. What comes out?', options: ['340 files', 'One item with one file', 'Nothing'], correct: 1, explain: 'The items are written into a single file.', hint: 'How many spreadsheets does one report need?' },
    { q: 'Extracting text from a PDF returns nothing. Likely reason?', options: ['The PDF is a scanned image', 'The workflow has no trigger', 'PDFs cannot be attached'], correct: 0, explain: 'A scan is a picture; there is no text layer to extract.', hint: 'Is there any text in the file, or just a photo of text?' },
  ],
})

export default {
  id: 'm4', n: 4, lite: true,
  title: 'Reliability, AI & Bigger Workflows',
  submodules: [
    { id: '4.1', title: 'When things break', video: v41 },
    { id: '4.2', title: 'Error workflows', video: v42 },
    { id: '4.3', title: 'AI in the loop', video: v43 },
    { id: '4.4', title: 'Sub-workflows', video: v44 },
    { id: '4.5', title: 'The Code node', video: v45 },
    { id: '4.6', title: 'Files and binary data', video: v46 },
  ],
  quiz: {
    passMark: 0.66,
    teachbackPrompt: 'Explain to a teammate how you would make a workflow you depend on fail safely and loudly — and how you would split a large one into reusable parts.',
    questions: [
      { sub: '4.1', q: 'A courier API times out now and then. Best setting?', options: ['Retry on fail, with a wait', 'Stop the workflow', 'Ignore the error'], correct: 0, explain: 'A temporary failure usually works on a second try.' },
      { sub: '4.1', q: 'A step that is retried must be…', options: ['Fast', 'Safe to run twice', 'The last node'], correct: 1, explain: 'If the first try worked but the reply was lost, the retry repeats it.' },
      { sub: '4.2', q: 'What makes an error workflow run?', options: ['A schedule', 'Another workflow failing', 'A webhook'], correct: 1, explain: 'It starts with an Error Trigger and runs when a linked workflow fails.' },
      { sub: '4.2', q: 'Zero rows arrived, but nothing errored. How do you raise the alarm?', options: ['Retry', 'Stop and Error', 'Merge'], correct: 1, explain: 'Stop and Error fails the workflow on purpose, with your own message.' },
      { sub: '4.3', q: 'What should an AI step in a workflow return?', options: ['A long explanation', 'A value from a fixed list the next node can test', 'Nothing'], correct: 1, explain: 'Structured, expected output keeps the rest of the workflow reliable.' },
      { sub: '4.3', q: 'A model suggests refunding a customer. What happens next?', options: ['The refund is issued', 'A person approves or rejects it', 'The workflow stops'], correct: 1, explain: 'Irreversible actions wait for human approval.' },

      { sub: '4.4', q: 'Why move repeated steps into a sub-workflow?', options: ['To fix them once instead of in every copy', 'To make them run twice', 'To avoid using a trigger'], correct: 0, explain: 'One shared sub-workflow means one place to change.' },
      { sub: '4.4', q: 'What does a good sub-workflow have?', options: ['As many jobs as possible', 'One job, a clear input and a clear output', 'No output'], correct: 1, explain: 'That is what makes it reusable and testable.' },
      { sub: '4.5', q: 'A node exists for the job. Should you use the Code node instead?', options: ['Yes, code is always better', 'No — use the node', 'Only on Mondays'], correct: 1, explain: 'Nodes are easier for others to read and maintain.' },
      { sub: '4.5', q: 'What must every Code node do?', options: ['Return items', 'Call an API', 'Contain a password'], correct: 0, explain: 'Without returned items the next node receives nothing.' },
      { sub: '4.6', q: 'Which node turns a spreadsheet file into items?', options: ['Extract from File', 'Convert to File', 'Switch'], correct: 0, explain: 'Extract: file → items. Convert: items → file.' },
      { sub: '4.6', q: 'After a node in the middle, the attachment is gone. What do you check?', options: ['Whether that node passed the file on', 'The trigger schedule', 'The workflow name'], correct: 0, explain: 'A file travels with the item only if each node keeps it attached.' },
    ],
  },
  reviews: [],
}
